<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lukas Arnold">
<meta name="author" content="Simone Arnold">
<meta name="author" content="Florian Bagemihl">
<meta name="author" content="Matthias Baitsch">
<meta name="author" content="Marc Fehr">
<meta name="author" content="Maik Poetzsch">
<meta name="author" content="Sebastian Seipel">

<title>Methodenbaustein Einlesen strukturierter Datensätze</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="einlesen-strukturierter-datensätze_files/libs/clipboard/clipboard.min.js"></script>
<script src="einlesen-strukturierter-datensätze_files/libs/quarto-html/quarto.js"></script>
<script src="einlesen-strukturierter-datensätze_files/libs/quarto-html/popper.min.js"></script>
<script src="einlesen-strukturierter-datensätze_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="einlesen-strukturierter-datensätze_files/libs/quarto-html/anchor.min.js"></script>
<link href="einlesen-strukturierter-datensätze_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="einlesen-strukturierter-datensätze_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="einlesen-strukturierter-datensätze_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="einlesen-strukturierter-datensätze_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="einlesen-strukturierter-datensätze_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#voraussetzungen" id="toc-voraussetzungen" class="nav-link active" data-scroll-target="#voraussetzungen"><span class="header-section-number">1</span> Voraussetzungen</a></li>
  <li><a href="#lernziele" id="toc-lernziele" class="nav-link" data-scroll-target="#lernziele"><span class="header-section-number">2</span> Lernziele</a></li>
  <li><a href="#einleitung" id="toc-einleitung" class="nav-link" data-scroll-target="#einleitung"><span class="header-section-number">3</span> Einleitung</a></li>
  <li><a href="#grundlagen-merkmale-von-datensätzen" id="toc-grundlagen-merkmale-von-datensätzen" class="nav-link" data-scroll-target="#grundlagen-merkmale-von-datensätzen"><span class="header-section-number">4</span> Grundlagen: Merkmale von Datensätzen</a>
  <ul class="collapse">
  <li><a href="#technisches-format" id="toc-technisches-format" class="nav-link" data-scroll-target="#technisches-format"><span class="header-section-number">4.1</span> Technisches Format</a></li>
  <li><a href="#struktur" id="toc-struktur" class="nav-link" data-scroll-target="#struktur"><span class="header-section-number">4.2</span> Struktur</a>
  <ul class="collapse">
  <li><a href="#eindimensionale-datensätze" id="toc-eindimensionale-datensätze" class="nav-link" data-scroll-target="#eindimensionale-datensätze">Eindimensionale Datensätze</a></li>
  <li><a href="#eindimensionale-daten-einlesen-mit-python" id="toc-eindimensionale-daten-einlesen-mit-python" class="nav-link" data-scroll-target="#eindimensionale-daten-einlesen-mit-python">Eindimensionale Daten einlesen mit Python</a></li>
  <li><a href="#zweidimensionale-datensätze" id="toc-zweidimensionale-datensätze" class="nav-link" data-scroll-target="#zweidimensionale-datensätze">Zweidimensionale Datensätze</a></li>
  <li><a href="#long--und-wide-format" id="toc-long--und-wide-format" class="nav-link" data-scroll-target="#long--und-wide-format">long- und wide-Format</a></li>
  <li><a href="#übung-zweidimensionale-datensätze" id="toc-übung-zweidimensionale-datensätze" class="nav-link" data-scroll-target="#übung-zweidimensionale-datensätze">Übung zweidimensionale Datensätze</a></li>
  <li><a href="#drei--und-mehrdimensionale-datensätze" id="toc-drei--und-mehrdimensionale-datensätze" class="nav-link" data-scroll-target="#drei--und-mehrdimensionale-datensätze">Drei- und mehrdimensionale Datensätze</a></li>
  <li><a href="#bilddaten-einlesen" id="toc-bilddaten-einlesen" class="nav-link" data-scroll-target="#bilddaten-einlesen">Bilddaten einlesen</a></li>
  </ul></li>
  <li><a href="#sec-datentyp" id="toc-sec-datentyp" class="nav-link" data-scroll-target="#sec-datentyp"><span class="header-section-number">4.3</span> Datentyp</a>
  <ul class="collapse">
  <li><a href="#sec-missing" id="toc-sec-missing" class="nav-link" data-scroll-target="#sec-missing">Fehlende Werte</a></li>
  <li><a href="#fehlende-werte-in-der-praxis" id="toc-fehlende-werte-in-der-praxis" class="nav-link" data-scroll-target="#fehlende-werte-in-der-praxis">Fehlende Werte in der Praxis</a></li>
  </ul></li>
  <li><a href="#sec-metadaten" id="toc-sec-metadaten" class="nav-link" data-scroll-target="#sec-metadaten"><span class="header-section-number">4.4</span> Metadaten</a></li>
  </ul></li>
  <li><a href="#strukturierte-datensätze-einlesen-die-module-numpy-pandas-und-glob" id="toc-strukturierte-datensätze-einlesen-die-module-numpy-pandas-und-glob" class="nav-link" data-scroll-target="#strukturierte-datensätze-einlesen-die-module-numpy-pandas-und-glob"><span class="header-section-number">5</span> Strukturierte Datensätze einlesen: die Module NumPy, Pandas und glob</a>
  <ul class="collapse">
  <li><a href="#datentypen" id="toc-datentypen" class="nav-link" data-scroll-target="#datentypen"><span class="header-section-number">5.1</span> Datentypen</a></li>
  <li><a href="#dateien-lesen-und-schreiben" id="toc-dateien-lesen-und-schreiben" class="nav-link" data-scroll-target="#dateien-lesen-und-schreiben"><span class="header-section-number">5.2</span> Dateien lesen und schreiben</a></li>
  <li><a href="#umgang-mit-fehlenden-werten" id="toc-umgang-mit-fehlenden-werten" class="nav-link" data-scroll-target="#umgang-mit-fehlenden-werten"><span class="header-section-number">5.3</span> Umgang mit fehlenden Werten</a>
  <ul class="collapse">
  <li><a href="#numpy-1" id="toc-numpy-1" class="nav-link" data-scroll-target="#numpy-1">NumPy</a></li>
  <li><a href="#zugriff-auf-mehrere-lokale-dateien-modul-glob" id="toc-zugriff-auf-mehrere-lokale-dateien-modul-glob" class="nav-link" data-scroll-target="#zugriff-auf-mehrere-lokale-dateien-modul-glob">Zugriff auf mehrere lokale Dateien: Modul glob</a></li>
  </ul></li>
  <li><a href="#datentypen-erkennen-und-festlegen" id="toc-datentypen-erkennen-und-festlegen" class="nav-link" data-scroll-target="#datentypen-erkennen-und-festlegen"><span class="header-section-number">5.4</span> Datentypen erkennen und festlegen</a>
  <ul class="collapse">
  <li><a href="#numpy-2" id="toc-numpy-2" class="nav-link" data-scroll-target="#numpy-2">NumPy</a></li>
  <li><a href="#pandas-1" id="toc-pandas-1" class="nav-link" data-scroll-target="#pandas-1">Pandas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#datensätze-organisieren" id="toc-datensätze-organisieren" class="nav-link" data-scroll-target="#datensätze-organisieren"><span class="header-section-number">6</span> Datensätze organisieren</a>
  <ul class="collapse">
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data"><span class="header-section-number">6.1</span> Tidy data</a></li>
  <li><a href="#das-modul-pandas" id="toc-das-modul-pandas" class="nav-link" data-scroll-target="#das-modul-pandas"><span class="header-section-number">6.2</span> Das Modul Pandas</a>
  <ul class="collapse">
  <li><a href="#in-pandas" id="toc-in-pandas" class="nav-link" data-scroll-target="#in-pandas">in Pandas</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#datumsformat" id="toc-datumsformat" class="nav-link" data-scroll-target="#datumsformat"><span class="header-section-number">7</span> Datumsformat</a></li>
  <li><a href="#räumliche-daten" id="toc-räumliche-daten" class="nav-link" data-scroll-target="#räumliche-daten"><span class="header-section-number">8</span> Räumliche Daten</a></li>
  <li><a href="#strategien-der-fehlersuche-und-bereinigung" id="toc-strategien-der-fehlersuche-und-bereinigung" class="nav-link" data-scroll-target="#strategien-der-fehlersuche-und-bereinigung"><span class="header-section-number">9</span> Strategien der Fehlersuche und Bereinigung</a></li>
  <li><a href="#das-wichtigste-vielleicht-als-video" id="toc-das-wichtigste-vielleicht-als-video" class="nav-link" data-scroll-target="#das-wichtigste-vielleicht-als-video"><span class="header-section-number">10</span> Das Wichtigste (vielleicht als Video)</a></li>
  <li><a href="#lernzielkontrolle" id="toc-lernzielkontrolle" class="nav-link" data-scroll-target="#lernzielkontrolle"><span class="header-section-number">11</span> Lernzielkontrolle</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Methodenbaustein Einlesen strukturierter Datensätze</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor:innen</div>
    <div class="quarto-title-meta-contents">
             <p>Lukas Arnold </p>
             <p>Simone Arnold </p>
             <p>Florian Bagemihl </p>
             <p>Matthias Baitsch </p>
             <p>Marc Fehr </p>
             <p>Maik Poetzsch </p>
             <p>Sebastian Seipel </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Veröffentlichungsdatum</div>
    <div class="quarto-title-meta-contents">
      <p class="date">13. September 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="Lizenz" class="border">
<div>

</div>
<div class="quarto-layout-panel" data-layout="[20, 80]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 20.0%;justify-content: center;">
<p><img src="skript/00-bilder/CC-BY.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 80.0%;justify-content: flex-start;">
<p>Bausteine Computergestützter Datenanalyse von Lukas Arnold, Simone Arnold, Florian Bagemihl, Matthias Baitsch, Marc Fehr, Maik Poetzsch und Sebastian Seipel. Methodenbaustein Einlesen strukturierter Datensätze von Maik Poetzsch ist lizensiert unter <a href="https://creativecommons.org/licenses/by/4.0/deed.de">CC BY 4.0</a>. Das Werk ist abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/m-Einlesen-strukturierter-Datens-tze">GitHub</a>. Ausgenommen von der Lizenz sind alle Logos und anders gekennzeichneten Inhalte. 2024</p>
</div>
</div>
</div>
<p>Zitiervorschlag</p>
<p>Arnold, Lukas, Simone Arnold, Matthias Baitsch, Marc Fehr, Maik Poetzsch, und Sebastian Seipel. 2024. „Bausteine Computergestützter Datenanalyse. Methodenbaustein Einlesen strukturierter Datensätze“. <a href="https://github.com/bausteine-der-datenanalyse/m-Einlesen-strukturierter-Datens-tze" class="uri">https://github.com/bausteine-der-datenanalyse/m-Einlesen-strukturierter-Datens-tze</a>.</p>
<p>BibTeX-Vorlage</p>
<pre><code>@misc{BCD-m-einlesen-strukturierter-datensätze-2024,
 title={Bausteine Computergestützter Datenanalyse. Methodenbaustein Einlesen strukturierter Datensätze},
 author={Arnold, Lukas and Arnold, Simone and Baitsch, Matthias and Fehr, Marc and Poetzsch, Maik and Seipel, Sebastian},
 year={2024},
 url={https://github.com/bausteine-der-datenanalyse/m-Einlesen-strukturierter-Datens-tze}} </code></pre>
</div>
<div style="page-break-after: always;"></div>
<section id="voraussetzungen" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Voraussetzungen</h1>
<p>Die Bearbeitungszeit dieses Bausteins beträgt circa <strong>Platzhalter</strong>. Für die Bearbeitung dieses Bausteins werden folgende Bausteine vorausgesetzt und die genannten Bibliotheken verwendet:</p>
<ul>
<li><p>Werkzeugbaustein Python</p>
<ul>
<li><p>Modul os</p></li>
<li><p>Modul Pandas</p></li>
<li><p>Modul Matplotlib</p></li>
</ul></li>
</ul>
<p>Im Baustein werden <strong>XY</strong> Daten verwendet.</p>
<p>Querverweis auf:</p>
<ul>
<li><p>w-NumPy</p></li>
<li><p>w-Pandas</p></li>
</ul>
</section>
<section id="lernziele" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Lernziele</h1>
<p>In diesem Baustein lernen Sie …</p>
<ul>
<li><p>Datensätze unterschiedlicher Struktur und Formate einzulesen, zu bearbeiten und zu speichern.</p></li>
<li><p>den Unterschied zwischen identifizierenden und gemessenen Variablen kennen sowie Datensätze ins long- und wide-Format zu konvertieren.</p></li>
<li><p>das System tidy data kennen.</p></li>
<li><p>typische Probleme beim Einlesen von Datensätzen und Strategien zu deren Lösung kennen.</p></li>
</ul>
</section>
<section id="einleitung" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Einleitung</h1>
<p>2016 stellte eine Studie fest, dass ein Fünftel aller wissenschaftlichen Artikel im Bereich der Genetik auf der Grundlage von durch die Tabellenkalkulation Excel verfälschten Daten durchgeführt wurde <span class="citation" data-cites="Ziemann-2016">(<a href="#ref-Ziemann-2016" role="doc-biblioref">Ziemann, Eren, und El-Osta 2016</a>)</span>. Genbezeichnungen wie “MARCH1” wurden fälschlicherweise in ein Datumsformat umgewandelt. 2021 wurde diese Schätzung des Anteils betroffener Arbeiten sogar auf 30 Prozent angehoben. (<a href="https://www.heise.de/news/Excel-wandelt-Genbezeichnungen-in-Datumsangaben-um-Problem-groesser-als-gedacht-6165902.html">heise online</a>)</p>
<p>Am Beginn der computergestützten Datenanalyse steht das Einlesen von Daten aus Dateien. In der Praxis ist das Einlesen von Daten alles andere als trivial. Daten werden in einer Vielzahl von Dateiformaten gespeichert. Deshalb ist es in der Datenanalyse erforderlich, mit verschiedenen Dateiformaten umgehen zu können: mit wenigen Kilobyte großen Textdateien, offenen und proprietären Formaten gängiger Büroanwendungen und mehreren hundert Megabyte großen Dateien in speziell für den Austausch wissenschaftlicher Daten entwickelten Formaten. Programmiersprachen wie Python und R bringen verschiedene Werkzeuge zum Lesen, Bearbeiten und Speichern von verschiedenen Dateiformaten mit. Spezialisierte Pakete ergänzen den Werkzeugkasten.</p>
<p>Die praktischen Herausforderungen der Datenanalyse beschränken sich jedoch nicht nur auf technische Aspekte. Oftmals bereitet der innere Aufbau von Datensätzen die größten Schwierigkeiten. Ein wichtiger Bestandteil des Einlesens strukturierter Datensätze besteht darin, Fehler im Datensatz zu suchen und ggf. zu bereinigen. Dasu und Johnson schreiben:</p>
<div>

</div>
<div class="border quarto-layout-panel" data-layout="[5, 90, 5]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“Unfortunately, the data set is usually dirty, composed of many tables, and has unknown properties. Before any results can be produced, the data must be cleaned and explored—often a long and difficult task. […] In our experience, the tasks of exploratory data mining and data cleaning constitute 80% of the effort that determines 80% of the value of the ultimate data mining results.” (<span class="citation" data-cites="Dasu-Johnson-2003">Dasu und Johnson (<a href="#ref-Dasu-Johnson-2003" role="doc-biblioref">2003</a>)</span>, S. ix)</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Das Einlesen strukturierter Datensätze umfasst somit den gesamten Prozess des technischen Zugriffs auf Dateien, der Organisation, Fehlersuche und -korrektur sowie des Abspeicherns der Daten in einer für die weitere Bearbeitung geeigneten Form.</p>
</section>
<section id="grundlagen-merkmale-von-datensätzen" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Grundlagen: Merkmale von Datensätzen</h1>
<p>Bevor wir uns mit den praktischen Herausforderungen des Einlesens strukturierter Datensätze beschäftigten, werden zunächst einige Merkmale von Datensätzen behandelt, um ein grundlegendes Verständnis der Begrifflichkeiten zu schaffen und den Umgang der in der Basis von Python enthaltenen Werkzeuge zu vermitteln.</p>
<div id="imp-Datensatz" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition&nbsp;1: Datensatz
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ein Datensatz ist eine Sammlung zusammengehöriger Daten. Datensätze enthalten einer oder mehreren Variablen zugeordnete Werte. Jeder Datensatz besitzt ein technisches Format, eine Struktur, mindestens eine Variable und mindestens einen Wert.</p>
</div>
</div>
<section id="technisches-format" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="technisches-format"><span class="header-section-number">4.1</span> Technisches Format</h2>
<p>Das technische Format eines Datensatzes gibt vor, mit welchen Mitteln Daten eingelesen, bearbeitet und gespeichert werden können. Einige Beispiele sind:</p>
<ul>
<li><p>Druckerzeugnis, z. B. Telefonbuch: manuelles Ablesen von Name und Telefonnummer, irreversible Bearbeitung per Stift</p></li>
<li><p>Lochkarte, z. B. Parkschein: Lesegerät erkennt Lochung und gewährt eine Freistunde, irreversible Bearbeitung mit Stanzgerät</p></li>
<li><p>Textdatei, z. B. Einwohnerzahl nach Bundesländern: Kann mit einer Vielzahl von Computerprogrammen wie Texteditor, Tabellenkalkulationsprogramm oder Programmierumgebung eingelesen, bearbeitet und gespeichert werden.</p></li>
<li><p>Hierarchical Data Format HDF5, z. B. räumliche Daten zur Blitzdichte: benötigt spezialisierte Programme oder Pakete</p></li>
</ul>
</section>
<section id="struktur" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="struktur"><span class="header-section-number">4.2</span> Struktur</h2>
<p>Datensätze speichern Daten in einer definierten n-dimensionalen Struktur.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/slicing_mf_mp.png" class="img-fluid figure-img"></p>
<figcaption>n-dimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. 2024</p>
</div>
<section id="eindimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="eindimensionale-datensätze">Eindimensionale Datensätze</h3>
<p>Die einfachste Form sind eindimensionale Datensätze, die in einer <strong>Liste</strong> Werte einer einzigen Variablen zuordnen. Eindimensionale Datensätze verfügen lediglich über eine Achse: den Index, über den Elemente angesprochen werden können.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/eindimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>eindimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Beispiele eindimensionaler Datensätze sind ein Einkaufszettel oder die Urliste eines Würfelexperiments. Über den Index kann beispielsweise das Würfelergebnis an der Indexposition 2 ausgegeben werden.</p>
<div id="a2b87431" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>( <span class="op">*</span>( Augen <span class="op">:=</span> [<span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>] ) )</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Das Würfelergebnis an Indexposition 2 lautet: </span><span class="sc">{</span>Augen[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>6 2 1 2
Das Würfelergebnis an Indexposition 2 lautet: 1</code></pre>
</div>
</div>
</section>
<section id="eindimensionale-daten-einlesen-mit-python" class="level3">
<h3 class="anchored" data-anchor-id="eindimensionale-daten-einlesen-mit-python">Eindimensionale Daten einlesen mit Python</h3>
<p>Maya und Hans haben je sechs Mal einen Würfel geworfen und ihre Wurfergebnisse in einer .txt-Datei protokolliert. Wir wollen mit die Dateien mit Python auswerten, um zu bestimmen, wer von beiden in Summe die höchste Augenzahl erreicht hat.</p>
<table class="table">
<thead>
<tr class="header">
<th>Daten</th>
<th>Dateiname</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Würfelergebnisse Maya</td>
<td>dice-maya.txt</td>
</tr>
<tr class="even">
<td>Würfelergebnisse Hans</td>
<td>dice-hans.txt</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<div class="border">
<p>Um mit Python auf eine Datei zuzugreifen, muss diese fürs Lesen oder Schreiben geöffnet werden. Dazu wird in Python die Funktion <a href="https://docs.python.org/3/library/functions.html#open">open</a> verwendet. Diese nimmt zwei Argumente, den Pfad der Datei und den Zugriffsmodus, an und liefert ein <a href="https://docs.python.org/3/glossary.html#term-file-object">Dateiobjekt</a> zurück. Aus dem Dateiobjekt werden dann die Inhalte der Datei ausgelesen.</p>
<section id="dateipfad" class="level4">
<h4 class="anchored" data-anchor-id="dateipfad">Dateipfad</h4>
<p>Der lokale Dateipfad wird ausgehend vom aktuellen Arbeitsverzeichnis angegeben.</p>
<div id="2eb88c9d" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>pfad_maya <span class="op">=</span> <span class="st">"skript/01-daten/dice-maya.txt"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>pfad_hans <span class="op">=</span> <span class="st">"skript/01-daten/dice-hans.txt"</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tip-wd-Python" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;1: Arbeitsverzeichnis in Python ermitteln und wechseln
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Der Pfad des aktuellen Arbeitsverzeichnisses kann mit dem Modul os mittels <code>os.getcwd()</code> ermittelt werden (hier ohne Ausgabe). Mit <code>os.chdir('neuer_pfad')</code> kann das Arbeitsverzeichnis ggf. gewechselt werden. Die korrekte Formatierung des Pfads erkennen Sie an der Ausgabe von <code>os.getcwd()</code>.</p>
<div id="b2649330" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(os.getcwd())</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="zugriffsmodus" class="level4">
<h4 class="anchored" data-anchor-id="zugriffsmodus">Zugriffsmodus</h4>
<p>Als Zugriffsmodus stehen unter anderem folgende Optionen zur Verfügung:</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 78%">
</colgroup>
<thead>
<tr class="header">
<th>Modus</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>r</code></td>
<td>lesender Zugriff</td>
</tr>
<tr class="even">
<td><code>w</code></td>
<td>Schreibzugriff, Datei wird überschrieben</td>
</tr>
<tr class="odd">
<td><code>x</code></td>
<td>Erzeugt die Datei, Fehlermeldung, wenn die Datei bereits existiert</td>
</tr>
<tr class="even">
<td><code>a</code></td>
<td>Schreibzugriff, Inhalte werden angehängt</td>
</tr>
<tr class="odd">
<td><code>b</code></td>
<td>Binärmodus (z. B. für Grafiken)</td>
</tr>
<tr class="even">
<td><code>t</code></td>
<td>Textmodus, default</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p>Die Zugriffsmodi können auch kombiniert werden. Weitere Informationen dazu finden Sie in der <a href="https://docs.python.org/3/library/functions.html#open">Dokumentation</a>. Sofern nicht im Binärmodus auf Dateien zugegriffen wird, liefert die Funktion <code>open()</code> den Dateiinhalt als string zurück.</p>
<p>Im Lesemodus wird ein Datenobjekt erzeugt.</p>
<div id="fb1a7bd8" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>daten_maya <span class="op">=</span> <span class="bu">open</span>(pfad_maya, mode <span class="op">=</span> <span class="st">'r'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_maya)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;_io.TextIOWrapper name='skript/01-daten/dice-maya.txt' mode='r' encoding='cp1252'&gt;</code></pre>
</div>
</div>
<p>Wenn das Datenobjekt <code>daten_maya</code> der Funktion <code>print()</code> übergeben wird, gibt Python die Klasse des Objekts zurück, in diesem Fall also _io.TextIOWrapper. Diese Klasse stammt aus dem Modul io und ist für das Lesen und Schreiben von Textdateien zuständig. Ebenfalls werden der Dateipfad, der Zugriffsmodus und die Enkodierung der Datei ausgegeben. Sollte die Enkodierung nicht automatisch als UTF-8 erkannt werden, kann diese mit dem Argument <code>encoding = 'UTF-8'</code> übergeben werden.</p>
<div id="c38cbb1e" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>daten_maya <span class="op">=</span> <span class="bu">open</span>(pfad_maya, mode <span class="op">=</span> <span class="st">'r'</span>, encoding <span class="op">=</span> <span class="st">'UTF-8'</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_maya)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;_io.TextIOWrapper name='skript/01-daten/dice-maya.txt' mode='r' encoding='UTF-8'&gt;</code></pre>
</div>
</div>
<p>Die Attribute der Datei können mit entsprechenden Befehlen abgerufen werden.</p>
<div id="a45d29b2" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dateipfad: </span><span class="sc">{</span>daten_maya<span class="sc">.</span>name<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Dateiname: </span><span class="sc">{</span>os<span class="sc">.</span>path<span class="sc">.</span>basename(daten_maya.name)<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Datei ist geschlossen: </span><span class="sc">{</span>daten_maya<span class="sc">.</span>closed<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Zugriffsmodus: </span><span class="sc">{</span>daten_maya<span class="sc">.</span>mode<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dateipfad: skript/01-daten/dice-maya.txt
Dateiname: dice-maya.txt
Datei ist geschlossen: False
Zugriffsmodus: r</code></pre>
</div>
</div>
</section>
<section id="daten-ausgeben" class="level4">
<h4 class="anchored" data-anchor-id="daten-ausgeben">Daten ausgeben</h4>
<p>Um den Dateiinhalt auszugeben, kann das Datenobjekt mit einer Schleife zeilenweise durchlaufen und ausgegeben werden. (Die Datei dice-maya hat nur eine Zeile.)</p>
<div id="4e92e980" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> zeile <span class="kw">in</span> daten_maya:</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Inhalt Zeile </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">, mit </span><span class="sc">{</span><span class="bu">len</span>(zeile)<span class="sc">}</span><span class="ss"> Zeichen:"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(zeile)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    i <span class="op">+=</span> <span class="dv">1</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Inhalt Zeile 0, mit 28 Zeichen:
"5", "6", "2", "1", "4", "5"</code></pre>
</div>
</div>
<p>Dies ist jedoch für größere Dateien nicht sonderlich praktikabel. Die Ausgabe einzelner Zeilen mit der Funktion <code>print()</code> kann aber nützlich sein, um die genaue Formatierung der Zeichenkette zu prüfen. In diesem Fall hat Maya ihre Daten in Anführungszeichen gesetzt und mit einem Komma voneinander getrennt.</p>
<div id="tip-zeilenweise" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2: Daten kontrollieren
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Beim Einlesen goßer Datensätze sollten nicht nur die erste(n) Zeile(n) des Datensatzes, sondern auch Ausschnitte aus der Mitte und dem Ende kontrolliert werden. Dies hilft, Fehler etwa bei der Umwandlung von Dezimal- und Tausendertrennzeichen, des Datumsformats oder eine unerwartete Anzahl fehlender Werte und sonstige Auffälligkeiten zu identifizieren.</p>
</div>
</div>
</div>
</section>
<section id="daten-einlesen" class="level4">
<h4 class="anchored" data-anchor-id="daten-einlesen">Daten einlesen</h4>
<p>Um den gesamten Inhalt einer Datei einzulesen, kann die Methode <a href="https://docs.python.org/3/tutorial/inputoutput.html">datenobjekt.read()</a> verwendet werden. Die Methode hat als optionales Argument <code>.read(size)</code>. size wird als Ganzzahl übergeben und entsprechend viele Zeichen (im Binärmodus entsprechend viele Bytes) werden ggf. bis zum Dateiende ausgelesen.</p>
<div id="a060aaa7" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>augen_maya <span class="op">=</span> daten_maya.read()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"len(augen_maya): </span><span class="sc">{</span><span class="bu">len</span>(augen_maya)<span class="sc">}</span><span class="ch">\n\n</span><span class="ss">"</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Inhalt der Datei augen_maya:</span><span class="ch">\n</span><span class="sc">{</span>augen_maya<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>len(augen_maya): 0

Inhalt der Datei augen_maya:
</code></pre>
</div>
</div>
<p>Das hat offensichtlich nicht geklappt, der ausgelesene Dateiinhalt ist leer! Der Grund dafür ist, dass beim Lesen (und beim Schreiben) einer Datei der Dateizeiger die Datei durchläuft. Nachdem die Datei daten_maya im Abschnitt “Daten ausgeben” zeilenweise ausgegeben wurde, steht der Dateizeiger am Ende der Datei.</p>
<div id="wrn-Dateizeiger" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;1: Dateizeiger in Python
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wird eine Datei zeilenweise oder mit der Methode <code>.read()</code> ausgelesen, wird der Dateizeiger um die angegebene Zeichenzahl bzw. bis ans Ende der Datei bewegt. Wird beispielsweise ein Datensatz ‘daten’ geöffnet und mit der Methode <code>daten.read(3)</code> die ersten drei Zeichen ausgelesen, bewegt sich der Dateizeiger von der Indexposition 0 zur Indexposition 3 (bzw. steht jeweils davor).</p>
<div id="fig-Dateizeiger" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Dateizeiger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="skript/00-bilder/indexposition-0.png" class="img-fluid figure-img" alt="Dargestellt ist ein in fünf Blöcke unterteilter Streifen, der einen eindimensionalen Datensatz repräsentiert. Die Blöcke sind entlang der 0. Achse von links nach rechts mit 0 bis 4 beschriftet. Oberhalb steht links vom Block Null ein Pfeil mit der Beschriftung Indexposition Null"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="skript/00-bilder/indexposition-3.png" class="img-fluid figure-img" alt="Dargestellt ist der gleiche Streifen. Oberhalb steht links vom Block drei ein Pfeil mit der Beschriftung Indexposition drei"></p>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Dateizeiger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1: Bewegung des Dateizeigers beim Auslesen von drei Zeichen
</figcaption>
</figure>
</div>
<p>Die Methode <code>daten.tell()</code> gibt zurück, an welcher Position sich der Dateizeiger befindet.</p>
<p>Mit der Methode <code>daten.seek(offset, whence = 0)</code> wird der Zeiger an eine bestimmte Position gesetzt. Die Methode akzeptiert das Argument offset (Versatz) und das optionale Argument whence (woher), dessen Standardwert 0 (Dateianfang) ist. Für Zugriffe <strong>im Binärmodus</strong> (<code>open(pfad, mode = 'rb')</code>) kann das Argument whence außerdem die Werte 1 (aktuelle Position) oder 2 (Dateiende) annehmen.</p>
<ul>
<li><p><code>daten.seek(0, 0)</code> bezeichnet den Dateianfang</p></li>
<li><p><code>daten.seek(0, 1)</code> bezeichnet die aktuelle Position in der Datei</p></li>
<li><p><code>daten.seek(0, 2)</code> bezeichnet das Dateiende</p></li>
<li><p><code>daten.seek(-3, 2)</code> bezeichnet das dritte Zeichen vor dem Dateiende</p></li>
</ul>
</div>
</div>
<p>Wird der Dateizeiger mit der Methode <code>datenobjekt.seek(0)</code> an den Dateianfang gestellt, gelingt das Auslesen der Datei.</p>
<div id="d3efc858" class="cell" data-results="hold" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Position des Dateizeigers vor dem Zurücksetzen auf 0: </span><span class="sc">{</span>daten_maya<span class="sc">.</span>tell()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>daten_maya.seek(<span class="dv">0</span>)<span class="op">;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Position des Dateizeigers nach dem Zurücksetzen auf 0: </span><span class="sc">{</span>daten_maya<span class="sc">.</span>tell()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>augen_maya <span class="op">=</span> daten_maya.read()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Inhalt des Objekts augen_maya:</span><span class="ch">\n</span><span class="sc">{</span>augen_maya<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Position des Dateizeigers vor dem Zurücksetzen auf 0: 28
Position des Dateizeigers nach dem Zurücksetzen auf 0: 0
Inhalt des Objekts augen_maya:
"5", "6", "2", "1", "4", "5"</code></pre>
</div>
</div>
<p><strong>Geben Sie aus dem Datenobjekt daten_maya mit den Methoden .seek() und .read() die Zahlen and zweiter und dritter Stelle, also 6 und 2, aus.</strong></p>
<div id="tip-Musterlösung-Zeigerposition" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;3: Musterlösung Dateizeiger bewegen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="f743d4a3" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>daten_maya.seek(<span class="dv">6</span>, <span class="dv">0</span>)<span class="op">;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_maya.read(<span class="dv">1</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>daten_maya.seek(daten_maya.tell() <span class="op">+</span> <span class="dv">4</span>, <span class="dv">0</span>)<span class="op">;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_maya.read(<span class="dv">1</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>6
2</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Um Mayas Würfelergebnisse zu addieren, müssen die Zahlen extrahiert und in Ganzzahlen umgewandelt werden, da im Textmodus stets strings zurückgegeben werden.</p>
<div id="8a64edc8" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(augen_maya))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'str'&gt;</code></pre>
</div>
</div>
<p>Dazu werden mit der Methode <code>str.strip(")</code> das führende und abschließende Anführungszeichen entfernt sowie anschließend mit der Methode <code>str.split('", "')</code> der String in eine Liste aufgeteilt. Anschließend werden die Listenelemente in Ganzzahlen umgewandelt und summiert.</p>
<div id="1c51172c" class="cell" data-results="hold" data-execution_count="12">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"augen_maya:</span><span class="ch">\n</span><span class="sc">{</span>augen_maya<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>augen_maya <span class="op">=</span> augen_maya.strip(<span class="st">'"'</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">augen_maya.strip('</span><span class="ch">\"</span><span class="ss">'):</span><span class="ch">\n</span><span class="sc">{</span>augen_maya<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>augen_maya <span class="op">=</span> augen_maya.split(<span class="st">'", "'</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">augen_maya.split('</span><span class="ch">\"</span><span class="ss">, </span><span class="ch">\"</span><span class="ss">'):</span><span class="ch">\n</span><span class="sc">{</span>augen_maya<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>augen_maya_int <span class="op">=</span> []</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> augen_maya:</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  augen_maya_int.append(<span class="bu">int</span>(i))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">augen_maya_int:</span><span class="ch">\n</span><span class="sc">{</span>augen_maya_int<span class="sc">}</span><span class="ch">\n\n</span><span class="ss">Summe Augen: </span><span class="sc">{</span><span class="bu">sum</span>(augen_maya_int)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>augen_maya:
"5", "6", "2", "1", "4", "5"

augen_maya.strip('"'):
5", "6", "2", "1", "4", "5

augen_maya.split('", "'):
['5', '6', '2', '1', '4', '5']

augen_maya_int:
[5, 6, 2, 1, 4, 5]

Summe Augen: 23</code></pre>
</div>
</div>
</section>
<section id="datei-schließen" class="level4">
<h4 class="anchored" data-anchor-id="datei-schließen">Datei schließen</h4>
<p>Nach dem Zugriff auf die Datei, muss diese wieder geschlossen werden, um diese für andere Programme freizugeben.</p>
<div id="b6ca0d14" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>daten_maya.close()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="wrn-Schreiboperationen" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;2: Schreiboperationen mit Python
</div>
</div>
<div class="callout-body-container callout-body">
<p>Das Schließen einer Datei ist besonders für Schreiboperationen auf Datenobjekten wichtig. Andernfalls kann es passieren, dass Inhalte mit <code>datenobjekt.write()</code> nicht vollständig auf den Datenträger geschrieben werden. Siehe dazu die <a href="https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files">Dokumentation</a>.</p>
</div>
</div>
</section>
<section id="übung-eindimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="übung-eindimensionale-datensätze">Übung eindimensionale Datensätze</h3>
<p><strong>Welche Augenzahl hat Hans erreicht?</strong></p>
<p><strong>Die Musterlösung kann Marc machen</strong></p>
<div id="tip-Musterlösung-Augenzahlvergleich" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;4: Musterlösung Augenzahlvergleich
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Musterlösung von Marc</p>
</div>
</div>
</div>
<p><span class="citation" data-cites="Arnold-2023-funktionen-module-dateien">(<a href="#ref-Arnold-2023-funktionen-module-dateien" role="doc-biblioref">Arnold 2023a</a>)</span></p>
</section>
</div>
</section>
<section id="zweidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="zweidimensionale-datensätze">Zweidimensionale Datensätze</h3>
<p>Zweidimensionale Datensätze organisieren Werte in einer aus Zeilen und Spalten bestehenden <strong>Matrix</strong> oder einem <strong>Dataframe</strong> (<strong>Hinweis: das ist die Terminologie in R, in Python ist das nicht so einfach. Es gibt das Modul array</strong>). Eine Matrix enthält nur einen Datentyp (bspw. Zahlen), ein Dataframe kann unterschiedliche Datentypen enthalten (bspw. Zahlen und Wahrheitswerte). In Pyhton stellt das Modul Pandas die DataFrame-Struktur bereit. <strong>hier Querverweis auf w-Pandas</strong></p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/zweidimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:45.0%"></p>
<figcaption>zweidimensionaler Datensatz</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Die meisten Datensätze sind zweidimensional. Typischerweise entspricht jede Spalte einer <strong>Variablen</strong> und jede Zeile einer <strong>Beobachtung</strong>. Variablen speichern alle Werte eines Merkmals, zum Beispiel des Würfelergebnisses. Beobachtungen speichern alle Werte, die für eine Beobachtungseinheit gemessen wurden, z. B. für eine Person. <span class="citation" data-cites="Wickham-2014">(<a href="#ref-Wickham-2014" role="doc-biblioref">Wickham 2014, 3</a>)</span></p>
<div id="32de41ef" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>messung1 <span class="op">=</span> pd.DataFrame({<span class="st">'Name'</span>: [<span class="st">'Hans'</span>, <span class="st">'Elke'</span>, <span class="st">'Jean'</span>, <span class="st">'Maya'</span>], <span class="st">'Geburtstag'</span>: [<span class="st">'26.02.'</span>, <span class="st">'14.03.'</span>, <span class="st">'30.12.'</span>, <span class="st">'07.09.'</span>], <span class="st">'Würfelfarbe'</span>: [<span class="st">'rosa'</span>, <span class="st">'rosa'</span>, <span class="st">'blau'</span>, <span class="st">'gelb'</span>], <span class="st">'Summe Augen'</span>: [<span class="dv">17</span>, <span class="dv">12</span>, <span class="dv">8</span>, <span class="dv">23</span>]})</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>messung1</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="68">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Über die Angabe der Indizes entlang der 0. und der 1. Achse kann die Summe der gewürfelten Augen einer Person ausgegeben werden.</p>
<div id="3690aac1" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Jean würfelte </span><span class="sc">{</span>messung1<span class="sc">.</span>iloc[<span class="dv">2</span>, <span class="dv">3</span>]<span class="sc">}</span><span class="ss"> Augen"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Jean würfelte 8 Augen</code></pre>
</div>
</div>
<p>Es ist aber auch möglich, zunächst eine Spalte auszuwählen und dann wie bei einem eindimensionalen Datensatz den Wert an einer Indexposition aufzurufen.</p>
<div id="6863ec14" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Jean würfelte </span><span class="sc">{</span>messung1[<span class="st">'Summe Augen'</span>][<span class="dv">2</span>]<span class="sc">}</span><span class="ss"> Augen"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Jean würfelte 8 Augen</code></pre>
</div>
</div>
</section>
<section id="long--und-wide-format" class="level3">
<h3 class="anchored" data-anchor-id="long--und-wide-format">long- und wide-Format</h3>
<p>Zweidimensionale Datensätze werden zumeist in einer aus Zeilen und Spalten bestehenden Matrix dargestellt. Den zeilenweise eingetragenen Beobachtungen werden Werte für die in den Spalten organisierten Variablen zugeordnet. Diese Art Daten darzustellen, wird wide-Format genannt: Mit jeder zusätzlich gemessenen Variablen wird der Datensatz breiter.</p>
<p>Eine andere Art Daten zu organisieren und über Daten nachzudenken, ist die Darstellung im long-Format. Einige Programme und Pakete erfordern Daten im long-Format oder profitieren zumindest davon beispielsweise bei der Erstellung von Grafiken. Schauen wir uns zunächst noch einmal den Datensatz messung1 im wide-Format an. Welche Beobachtungseinheiten gibt es? Welche Variablen wurden erhoben?</p>
<div id="4f2a02f2" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display" data-execution_count="71">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Vermutlich werden Sie davon ausgehen, dass die Beobachtungseinheiten Hans, Elke, Jean und Maya sind und die Variablen Geburtstag, Würfelfarbe und Summe Augen. Es ist aber auch denkbar, dass die Beobachtungseinheit Person mit 0, 1, 2 und 3 kodiert wurde (dem Zeilenindex des Datensatzes) und die Spalte Name ebenfalls eine der erhobenen Variablen ist. Ebenso könnte es nur zwei Variablen, Würfelfarbe und Summe Augen, geben, während die Spalten Name und Geburtstag die beobachteten Personen kodieren. Stellen Sie sich vor, es gäbe eine zweite Person mit dem Namen Hans. Dann könnten die Würfelergebnisse der Personen mit dem Namen Hans nur über den Geburtstag am 26.02. oder 11.11. korrekt zugeordnet werden.</p>
<div id="790cec9e" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>messung1 <span class="op">=</span> pd.DataFrame({<span class="st">'Name'</span>: [<span class="st">'Hans'</span>, <span class="st">'Elke'</span>, <span class="st">'Jean'</span>, <span class="st">'Maya'</span>, <span class="st">'Hans'</span>], <span class="st">'Geburtstag'</span>: [<span class="st">'26.02.'</span>, <span class="st">'14.03.'</span>, <span class="st">'30.12.'</span>, <span class="st">'07.09.'</span>, <span class="st">'11.11.'</span>], <span class="st">'Würfelfarbe'</span>: [<span class="st">'rosa'</span>, <span class="st">'rosa'</span>, <span class="st">'blau'</span>, <span class="st">'gelb'</span>, <span class="st">'rosa'</span>], <span class="st">'Summe Augen'</span>: [<span class="dv">12</span>, <span class="dv">17</span>, <span class="dv">8</span>, <span class="dv">23</span>, <span class="dv">7</span>]})</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>messung1</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="72">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Hans</td>
<td>11.11.</td>
<td>rosa</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Das long-Format macht diese Überlegungen explizit, indem identifizierende Variablen (identification variables, kurz: id vars) und gemessene Variablen (measure variables, kurz: measure vars oder value vars) unterschieden werden. Die Transformation eines Datensatzes aus dem wide-Format ins long-Format wird melting (schmelzen) genannt. Das Modul Pandas bietet die Funktion <code>pd.melt(frame, id_vars = None)</code>. Diese erwartet einen DataFrame. Im optionalen Argument <code>id_vars</code> wird angegeben, welche Spalten die identifizierenden Variablen sind.</p>
<div id="7e423ecc" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>messung1_long <span class="op">=</span> pd.melt(messung1, id_vars <span class="op">=</span> [<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>])</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>messung1_long</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="73">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Hans</td>
<td>11.11.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Hans</td>
<td>26.02.</td>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Elke</td>
<td>14.03.</td>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Jean</td>
<td>30.12.</td>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Maya</td>
<td>07.09.</td>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Hans</td>
<td>11.11.</td>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Im long-Format werden die gemessenen Variablen in der Spalte variable aufgeführt und deren Wert in der Spalte value eingetragen. Mit jeder zusätzlich erhobenen Variablen wird der Datensatz länger.</p>
<p>Wenn Sie die Unterscheidung von identifizierenden und gemessenen Variablen zu Ende denken, kann der Variablenname selbst als eine identifizierende Variable für den Wert in der Spalte value aufgefasst werden. Ein Datensatz kann als eine Struktur verstanden werden, die genau eine gemessene Variable, nämlich value, und eine Anzahl identifizierender Variablen besitzt. Dies kann im long-Format wie folgt dargestellt werden.</p>
<div id="91a28865" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>messung1_all_id <span class="op">=</span> pd.melt(messung1, id_vars <span class="op">=</span> [<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>])</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>messung1_all_id</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In dieser Darstellung wird beispielsweise der erste Wert 12 durch Name = Hans, Geburtstag = 26.02., Würfelfarbe = rosa und variable = Summe Augen identifiziert.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[70, 30]">
<div class="quarto-layout-row">
<div id="e0e8cf0d" class="cell quarto-layout-cell" data-execution_count="21" style="flex-basis: 70.0%;justify-content: center;">
<div class="cell-output cell-output-display" data-execution_count="75">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Geburtstag</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Würfelfarbe</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;" data-quarto-table-cell-role="th">0</td>
<td style="text-align: left;">Hans</td>
<td style="text-align: left;">26.02.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;" data-quarto-table-cell-role="th">1</td>
<td style="text-align: left;">Elke</td>
<td style="text-align: left;">14.03.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;" data-quarto-table-cell-role="th">2</td>
<td style="text-align: left;">Jean</td>
<td style="text-align: left;">30.12.</td>
<td style="text-align: left;">blau</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;" data-quarto-table-cell-role="th">3</td>
<td style="text-align: left;">Maya</td>
<td style="text-align: left;">07.09.</td>
<td style="text-align: left;">gelb</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<td style="text-align: left;" data-quarto-table-cell-role="th">4</td>
<td style="text-align: left;">Hans</td>
<td style="text-align: left;">11.11.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 30.0%;justify-content: center;">
<p><img src="skript/00-bilder/5f489ffabc91dec1ec2192dc4e993e00.jpg" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 70.0%;justify-content: flex-start;">
<!-- wow kommt wieder weg ;-) -->
</div>
</div>
</div>
<p><strong>Was passiert, wenn auch die Variable <code>Summe Augen</code> dem Argument <code>id_vars</code> übergeben wird?</strong></p>
<div id="tip-Antwort-all-id" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;5: Antwort
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Der Befehl <code>messung1_all_id = pd.melt(messung1, id_vars = ['Name', 'Geburtstag', 'Würfelfarbe', 'Summe Augen'])</code> produziert einen leeren Dataframe, weil keine gemessenen Werte verbleiben.</p>
</div>
</div>
</div>
<p>Auch der umgekehrte Fall ist möglich: Werden beim melting keine id_vars angegeben, werden alle Spalten als gemessene Variablen behandelt.</p>
<div id="3f591bac" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>messung1_no_id <span class="op">=</span> pd.melt(messung1)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>messung1_no_id</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="76">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Name</td>
<td>Hans</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Name</td>
<td>Elke</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Name</td>
<td>Jean</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Name</td>
<td>Maya</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Name</td>
<td>Hans</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Geburtstag</td>
<td>26.02.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Geburtstag</td>
<td>14.03.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Geburtstag</td>
<td>30.12.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Geburtstag</td>
<td>07.09.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Geburtstag</td>
<td>11.11.</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Die Umkehroperation zum melting wird casting (gießen) oder pivoting (schwenken) genannt. Dabei wird ein im long-Format vorliegender Datensatz in das wide-Format konvertiert. Die Pandas Funktion <code>pd.pivot(data, columns, index)</code> nimmt einen melted DataFrame entgegen und konveriert diesen aus den einzigartigen Werten in columns (= Spaltennamen des DataFrame im wide-Format) und den einzigartigen Werten in index (= Zeilenindex des DataFrame im wide-Format). Wird der Funktion keine Spalte für index übergeben, wird der bestehende Index des melted DataFrame verwendet (der mit 20 Zeilen natürlich viel zu lang ist.) Da das Objekt messung1_no_id keine geeignete Indexspalte besitzt, muss diese vor dem casting erzeugt werden. Dies ist mit der Methode <code>messung1_no_id.groupby('variable').cumcount()</code> möglich, die die Anzahl jeder Ausprägung in der übergebenen Spalte bei 0 beginnend durchzählt. (Ein direktes Ersetzen des Index ist auf diese Weise nicht möglich, da der Index des an <code>pd.pivot(data, columns, index)</code> übergebenen DataFrames keine Doppelungen enthalten darf.)</p>
<div id="ccf4dc81" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.pivot() benötigt einen Index oder benutzt den bestehenden Index, des melted_df, der zu lang ist</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Deshalb eine zusätzliche Spalte in messung1_no_id einfügen</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">## einfach: messung1_no_id['new_index'] = list(range(0, 5)) * 4 </span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co">## allgemein: messung1_no_id['new_index'] = messung1_no_id.groupby('variable').cumcount()</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalte new_index einfügen</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>messung1_no_id[<span class="st">'new_index'</span>] <span class="op">=</span> messung1_no_id.groupby(<span class="st">'variable'</span>).cumcount()</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="ss">f"Der Datensatz im long-Format mit zusätzlicher Spalte new_index:</span><span class="ch">\n</span><span class="sc">{</span>messung1_no_id<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># casting</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>messung1_cast <span class="op">=</span> pd.pivot(messung1_no_id, index <span class="op">=</span> <span class="st">'new_index'</span>, columns <span class="op">=</span> <span class="st">'variable'</span>, values <span class="op">=</span> <span class="st">'value'</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Der Datensatz im wide-Format:</span><span class="ch">\n</span><span class="sc">{</span>messung1_cast<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Der Datensatz im long-Format mit zusätzlicher Spalte new_index:
       variable   value  new_index
0          Name    Hans          0
1          Name    Elke          1
2          Name    Jean          2
3          Name    Maya          3
4          Name    Hans          4
5    Geburtstag  26.02.          0
6    Geburtstag  14.03.          1
7    Geburtstag  30.12.          2
8    Geburtstag  07.09.          3
9    Geburtstag  11.11.          4
10  Würfelfarbe    rosa          0
11  Würfelfarbe    rosa          1
12  Würfelfarbe    blau          2
13  Würfelfarbe    gelb          3
14  Würfelfarbe    rosa          4
15  Summe Augen      12          0
16  Summe Augen      17          1
17  Summe Augen       8          2
18  Summe Augen      23          3
19  Summe Augen       7          4

Der Datensatz im wide-Format:
variable  Geburtstag  Name Summe Augen Würfelfarbe
new_index                                         
0             26.02.  Hans          12        rosa
1             14.03.  Elke          17        rosa
2             30.12.  Jean           8        blau
3             07.09.  Maya          23        gelb
4             11.11.  Hans           7        rosa</code></pre>
</div>
</div>
<p>Das Ergebnis entspricht noch nicht dem ursprünglichen Datensatz im wide-Format. Um das Ausgangsformat wiederherzustellen, müssen die Spalten in die ursprüngliche Reihenfolge gebracht sowie der Index und dessen Beschriftung zurückgesetzt werden.</p>
<div id="ecc547f7" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalten anordnen, Index zurücksetzen</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>messung1_cast <span class="op">=</span> messung1_cast[[<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>, <span class="st">'Summe Augen'</span>]]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>messung1_cast.reset_index(drop <span class="op">=</span> <span class="va">True</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>messung1_cast.rename_axis(<span class="va">None</span>, axis <span class="op">=</span> <span class="dv">1</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Der Datensatz im wide-Format mit zurückgesetztem Index:</span><span class="ch">\n\n</span><span class="sc">{</span>messung1_cast<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Der Datensatz im wide-Format mit zurückgesetztem Index:

   Name Geburtstag Würfelfarbe Summe Augen
0  Hans     26.02.        rosa          12
1  Elke     14.03.        rosa          17
2  Jean     30.12.        blau           8
3  Maya     07.09.        gelb          23
4  Hans     11.11.        rosa           7</code></pre>
</div>
</div>
</section>
<section id="übung-zweidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="übung-zweidimensionale-datensätze">Übung zweidimensionale Datensätze</h3>
<p>Oben wurde das Objekt messung1_long mit dem Befehl <code>messung1_long = pd.melt(messung1, id_vars = ['Name', 'Geburtstag'])</code> angelegt.<br>
<strong>Benutzen Sie die Funktion</strong> <code>df.cast()</code>, <strong>um den Datensatz messung1 wieder ins wide-Format zu transformieren.</strong></p>
<div id="2344e5f9" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display" data-execution_count="79">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Hans</td>
<td>11.11.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Hans</td>
<td>26.02.</td>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Elke</td>
<td>14.03.</td>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Jean</td>
<td>30.12.</td>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Maya</td>
<td>07.09.</td>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Hans</td>
<td>11.11.</td>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<div id="tip-pivoting" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;6: Musterlösung zweidimensionale Datensätze
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="c66dcedb" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalte new_index einfügen</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>messung1_long[<span class="st">'new_index'</span>] <span class="op">=</span> messung1_long.groupby(<span class="st">'variable'</span>).cumcount()</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># casting</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>messung1_long_cast <span class="op">=</span> pd.pivot(messung1_long, index <span class="op">=</span> <span class="st">'new_index'</span>, columns <span class="op">=</span> <span class="st">'variable'</span>, values <span class="op">=</span> <span class="st">'value'</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalten anordnen, Index zurücksetzen</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>messung1_long_cast <span class="op">=</span> messung1_cast[[<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>, <span class="st">'Summe Augen'</span>]]</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>messung1_long_cast.reset_index(drop <span class="op">=</span> <span class="va">True</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>messung1_long_cast.rename_axis(<span class="va">None</span>, axis <span class="op">=</span> <span class="dv">1</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>messung1_long_cast</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="80">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Hans</td>
<td>11.11.</td>
<td>rosa</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="drei--und-mehrdimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="drei--und-mehrdimensionale-datensätze">Drei- und mehrdimensionale Datensätze</h3>
<p>Drei- oder mehrdimensionale Datensätze organisieren komplexe Datenstrukturen in sogenannten <strong>Arrays</strong>. Arrays sind n-dimensionale Datenstrukturen und damit zugleich ein Oberbegriff für eine Vielzahl von Datenstrukturen. So ist eine Liste ein eindimensionales Array, eine Matrix ein zweidimensionales Array und eine Excel-Datei mit mehreren Arbeitsblättern für jährlich erhobene Umfragedaten ein 3-dimensionales Array (Arbeitsblätter, Zeilen, Spalten). Arrays sind insbesondere für höherdimensionale Datenstrukturen von Bedeutung. Beispielsweise liegen Sensordaten häufig in mehrdimensionalen Strukturen vor. Abhängig vom verwendeten Modul können Arrays ein oder mehrer Datentypen enthalten.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/dreidimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>dreidimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Für drei- und mehrdimensionale Datenstrukturen werden häufig spezialisierte Datenformate verwendet, die in den Folgenden Abschnitten behandelt werden. Dies hat unter anderem den Grund, dass so leichter verschiedene Datentypen verarbeitet und mit Metadaten (siehe <a href="#sec-metadaten" class="quarto-xref">Kapitel&nbsp;4.4</a>) dokumentiert werden können.</p>
<p><strong>optional: Exkurs JSON <a href="https://docs.python.org/3/tutorial/inputoutput.html" class="uri">https://docs.python.org/3/tutorial/inputoutput.html</a></strong></p>
</section>
<section id="bilddaten-einlesen" class="level3">
<h3 class="anchored" data-anchor-id="bilddaten-einlesen">Bilddaten einlesen</h3>
<div class="border">
<p>Digitale Bilder liegen in Form eines dreidimensionalen Datensatzes vor. In Zeilen und Spalten liegen für jeden Pixel Farbwerte (Rot, Grün, Blau) und gegebenenfalls ein Alphawert vor (Rot, Grün, Blau, Alpha). Die Farbwerte liegen entweder im Bereich von 0 bis 1 oder von 0 bis 255 (8-Bit).</p>
<pre><code># Farbwerte für einen Pixel
[Rotwert, Grünwert, Blauwert]

# Eine Bildzeile mit drei Pixeln
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]]

# Ein Bild aus drei Zeilen und Spalten
[[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]],
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]],
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]]]</code></pre>
<p>Bilddateien können mit der Funktion <code>plt.imread()</code> aus dem Modul <code>matplotlib.pyplot</code> eingelesen werden.</p>
<div class="border">
<div id="a4234444" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>logo <span class="op">=</span> plt.imread(fname <span class="op">=</span> <span class="st">'skript/00-bilder/python-logo-and-wordmark-cc0-tm.png'</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>plt.imshow(logo)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="einlesen-strukturierter-datensätze_files/figure-html/cell-28-output-1.png" width="575" height="200" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Python Logo von Python Software Foundation steht unter der <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3</a>. Die Wort-Bild-Marke ist markenrechtlich geschützt: <a href="https://www.python.org/psf/trademarks/" class="uri">https://www.python.org/psf/trademarks/</a>. Das Werk ist abrufbar auf <a href="https://de.m.wikipedia.org/wiki/Datei:Python_logo_and_wordmark.svg">wikimedia</a>. 2008</p>
</div>
<p>&nbsp;</p>
<p>Die Struktur des Datensatzes kann mit dem Attribut <code>.shape</code> abgerufen werden.</p>
<div id="48a525a7" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(logo), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logo.shape)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'numpy.ndarray'&gt; 

(144, 486, 4)</code></pre>
</div>
</div>
<p>Die Daten wurden als NumPy.ndarray eingelesen. Das Logo hat 144 Zeilen, 486 Spalten und liegt im RGBA-Farbraum vor. Ein Ausschnitt der Daten sieht so aus:</p>
<div id="ae3e6c51" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logo[<span class="dv">50</span>:<span class="dv">52</span>, <span class="dv">50</span>:<span class="dv">52</span>, : ])</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[[0.21568628 0.44705883 0.63529414 1.        ]
  [0.21568628 0.44705883 0.63529414 1.        ]]

 [[0.21568628 0.44705883 0.63529414 1.        ]
  [0.21176471 0.44313726 0.6313726  1.        ]]]</code></pre>
</div>
</div>
<section id="übung-dreidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="übung-dreidimensionale-datensätze">Übung dreidimensionale Datensätze</h3>
<p>Über den Index der dritten Dimension können die Farbkanäle Rot, Grün und Blau ausgewählt und mit der Funktion <code>plt.imshow(cmap = 'Greys_r')</code> einzeln dargestellt werden. Das Argument <code>cmap = 'Greys_r'</code> weist die Funktion an, die invertierte Grauskala benutzen. Dadurch werden hohe Farbwerte hell und niedrige Farbwerte dunkel dargestellt. <strong>Versuchen Sie es einmal.</strong></p>
<div id="tip-logo" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;7: Musterlösung dreidimensionale Datensätze
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="c2db2d37" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>kanal <span class="op">=</span> [<span class="st">"Rotkanal"</span>, <span class="st">"Grünkanal"</span>, <span class="st">"Blaukanal"</span>]</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">9</span>, <span class="dv">6</span>))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.suptitle('Farbkanäle des Pythonlogos')</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  plt.subplot(<span class="dv">1</span>, <span class="dv">4</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  plt.imshow(logo[ :, :, i], cmap <span class="op">=</span> <span class="st">'Greys_r'</span>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  plt.title(label <span class="op">=</span> kanal[i])</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>plt.colorbar(shrink <span class="op">=</span> <span class="fl">0.15</span>)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="einlesen-strukturierter-datensätze_files/figure-html/cell-31-output-1.png" width="652" height="114" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><span class="citation" data-cites="Arnold-2023-numpy-dateien">(<a href="#ref-Arnold-2023-numpy-dateien" role="doc-biblioref">Arnold 2023b</a>)</span></p>
</section>
</div>
</section>
</section>
<section id="sec-datentyp" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-datentyp"><span class="header-section-number">4.3</span> Datentyp</h2>
<p>Der Datentyp gibt an, wie die in einem Datensatz einhaltenen Werte von Python interpretiert werden sollen. Beispielsweise kann der Wert “1” ein Zeichen, eine Ganzzahl, einen Wahrheitswert, den Monat Januar oder die Ausprägung einer kategorialen Variablen repräsentieren. Python unterstützt als vielseitig einsetzbare Programmiersprache zahlreiche Datentypen, die den Kategorien: numerics, sequences, mappings, classes, instances and exceptions zugeordnet sind. Nähere Informationen dazu finden Sie in der <a href="https://docs.python.org/3/library/stdtypes.html">Dokumentation</a>.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skript/00-bilder/python3-standard-type-hierarchy.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Datentypen in Python</figcaption>
</figure>
</div>
<p>Python 3. The standard type hierarchy. von Максим Пе ist lizensiert unter <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.de">CC BY SA 4.0</a> und abrufbar auf <a href="https://commons.wikimedia.org/wiki/File:Python_3._The_standard_type_hierarchy.png">wikimedia</a>. 2018</p>
</div>
<p>&nbsp;</p>
<p>Durch Module werden weitere Datentypen hinzugefügt. In der Datenanalyse häufig verwendete Datentypen sind:</p>
<ul>
<li><p>Zahlen: Ganzzahl, Fließkommazahlen</p></li>
<li><p>Wahrheitswerte</p></li>
<li><p>Zeichenketten</p></li>
<li><p>Datums- und Uhrzeitangaben</p></li>
<li><p>Kategorie<!-- Faktor in R--> (aus dem Modul <a href="https://pandas.pydata.org/docs/user_guide/categorical.html">Pandas</a>)</p></li>
</ul>
<p>Python enthält Funktionen, um den Datentyp eines Werts zu bestimmen und ggf. umzuwandeln. Einige dieser Funktionen werden exemplarisch vorgestellt.</p>
<div id="33449ed0" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> <span class="dv">67</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(a, <span class="bu">type</span>(a))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> a <span class="op">+</span> <span class="fl">1.8</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(b, <span class="bu">type</span>(b), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in Ganzzahlen mit int(): </span><span class="sc">{</span>( a <span class="op">:=</span> <span class="bu">int</span>(a) )<span class="sc">,</span> (b <span class="op">:=</span> <span class="bu">int</span>(b) )<span class="sc">}</span><span class="ss"> - Beachten Sie das Abschneiden der Nachkommastelle.</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in ASCII-Zeichen mit chr(): </span><span class="sc">{</span>( a <span class="op">:=</span> <span class="bu">chr</span>(a) )<span class="sc">,</span> ( b <span class="op">:=</span> <span class="bu">chr</span>(b) )<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in Zahlen mit ord(): </span><span class="sc">{</span>( a <span class="op">:=</span> <span class="bu">ord</span>(a) )<span class="sc">,</span> ( b <span class="op">:=</span> <span class="bu">ord</span>(b) )<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in Fließkommazahlen mit float(): </span><span class="sc">{</span>( a <span class="op">:=</span> <span class="bu">float</span>(a) )<span class="sc">,</span> ( b <span class="op">:=</span> <span class="bu">float</span>(b) )<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in Zeichen mit str(): </span><span class="sc">{</span>( a <span class="op">:=</span> <span class="bu">str</span>(a) )<span class="sc">,</span> ( b<span class="op">:=</span> <span class="bu">str</span>(b) )<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Umwandlung in Wahrheitswerte mit bool(): </span><span class="sc">{</span><span class="bu">bool</span>(a)<span class="sc">,</span> <span class="bu">bool</span>(b)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>67 &lt;class 'int'&gt;
68.8 &lt;class 'float'&gt; 

Umwandlung in Ganzzahlen mit int(): (67, 68) - Beachten Sie das Abschneiden der Nachkommastelle.

Umwandlung in ASCII-Zeichen mit chr(): ('C', 'D')

Umwandlung in Zahlen mit ord(): (67, 68)

Umwandlung in Fließkommazahlen mit float(): (67.0, 68.0)

Umwandlung in Zeichen mit str(): ('67.0', '68.0')

Umwandlung in Wahrheitswerte mit bool(): (True, True)</code></pre>
</div>
</div>
<p>Der Datentyp bestimmt zum einen den zulässigen Wertebereich einer Variablen. Beispielsweise sind 0 und 13 zulässige Ganzzahlen, aber keine gültigen Kodierungen des Monats. Zum anderen definiert der Datentyp, welche Operationen mit den Werten zulässig sind und wie diese von Python ausgeführt werden. Dies betrifft Operatoren und Funktionen.</p>
<div id="nte-operation-nach-datentyp" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel&nbsp;1: Datentypabhängige Operationen und Funktionen
</div>
</div>
<div class="callout-body-container callout-body">
<div id="a65022b9" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Der Operator + bewirkt die Addition von Zahlen</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span> <span class="op">+</span> <span class="dv">13</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Der Operator + bewirkt auch das Verketten von strings</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">str</span>(<span class="dv">1</span>) <span class="op">+</span> <span class="bu">str</span>(<span class="dv">13</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14
113</code></pre>
</div>
</div>
<p>Die Sortierfunktion arbeitet abhängig vom Datentyp.</p>
<div id="3e5b966a" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Liste von Monatskürzeln erstellen</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> pd.Series([ <span class="st">'07.06.2000'</span>, <span class="st">'12.01.2000'</span>, <span class="st">'11.02.2000'</span>, <span class="st">'04.09.2000'</span>, <span class="st">'10.03.2000'</span>, <span class="st">'03.10.2000'</span>, <span class="st">'09.04.2000'</span>, <span class="st">'08.05.2000'</span>, <span class="st">'06.07.2000'</span>, <span class="st">'05.08.2000'</span>, <span class="st">'02.11.2000'</span>, <span class="st">'01.12.2000'</span>])</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>dates <span class="op">=</span> pd.to_datetime(dates, <span class="bu">format</span> <span class="op">=</span> <span class="st">'</span><span class="sc">%d</span><span class="st">.%m.%Y'</span>)<span class="op">;</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Eine unsortierte Liste von Monatskürzeln:</span><span class="ch">\n</span><span class="sc">{</span><span class="bu">list</span>(dates.dt.strftime(<span class="st">"%b"</span>))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Die Liste alphabetisch sortiert:</span><span class="ch">\n</span><span class="sc">{</span><span class="bu">sorted</span>(<span class="bu">list</span>(dates.dt.strftime(<span class="st">"%b"</span>)))<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Die Liste als datetime-Objekt sortiert:</span><span class="ch">\n</span><span class="sc">{</span><span class="bu">list</span>(dates.sort_values().dt.strftime(<span class="st">"%b"</span>))<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Eine unsortierte Liste von Monatskürzeln:
['Jun', 'Jan', 'Feb', 'Sep', 'Mar', 'Oct', 'Apr', 'May', 'Jul', 'Aug', 'Nov', 'Dec']

Die Liste alphabetisch sortiert:
['Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep']

Die Liste als datetime-Objekt sortiert:
['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']</code></pre>
</div>
</div>
</div>
</div>
<p>Deshalb ist es beim Einlesen von Datensätzen wichtig, die korrekte Erkennung der Datentypen zu kontrollieren bzw. aktiv zu steuern.</p>
<p><strong>TO DO: Tipps für Strategien der Fehlersuche und -bereinigung sammeln</strong> <strong>Strategien der Fehlersuche und -bereinigung: Korrektes Einlesen der Datentypen prüfen (bspw. nicht erkanntes Datetime führt nicht zu einer Fehlermeldung, sondern zum Einlesen als object) bzw. diese explizit spezifizieren, da Operationen auch mit falschen Datentypen fehlerfrei ausgeführt werden können. Listen haben in Python keinen Datentyp, man muss jedes Element prüfen!</strong> <strong>Strategien der Fehlersuche und -bereinigung: Einhaltung des zulässigen Wertebereichs überprüfen (mit .describe) –&gt; guter Anfang, um Fehler im Datensatz zu finden (bspw. darf es keinen Monat 0 oder 13 geben).</strong></p>
<section id="sec-missing" class="level3">
<h3 class="anchored" data-anchor-id="sec-missing">Fehlende Werte</h3>
<p>Ein besonderer Datentyp ist der zur Repräsentation fehlender Werte. In Python wird zwischen nicht existenten und nicht definierten Werten unterschieden.</p>
<section id="nullwert-none" class="level4">
<h4 class="anchored" data-anchor-id="nullwert-none">Nullwert None</h4>
<p>Der sogenannte Nullwert in Python ist <code>None</code>. <code>None</code> ist sowohl ein Objekt, als auch ein Datentyp der Klasse ‘NoneType’.</p>
<div id="c406f4d9" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>test <span class="op">=</span> <span class="va">None</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(test))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'NoneType'&gt;</code></pre>
</div>
</div>
<p><code>None</code> repräsentiert nicht existente Werte und Objekte. Leere Objekte gehören nicht zum Datentyp <code>None</code>.</p>
<div id="e2d0cdc9" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>leere_liste <span class="op">=</span> []</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>leere_liste <span class="op">==</span> <span class="va">None</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="89">
<pre><code>False</code></pre>
</div>
</div>
<p><code>None</code> kann Funktionen als Argument übergeben oder von diesen als Rückgabewert ausgegeben werden. Operationen sind mit <code>None</code> jedoch nicht möglich.</p>
<div id="c98cbb49" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Operationen mit None führen zu Fehlermeldungen</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> my_plusone(item):</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>      result <span class="op">=</span> item <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">TypeError</span> <span class="im">as</span> error:</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>       <span class="bu">print</span>(<span class="st">"Der übergebene Wert führt zu der Fehlermeldung:</span><span class="ch">\n</span><span class="st">"</span>, error)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> result</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>my_plusone(<span class="va">None</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Der übergebene Wert führt zu der Fehlermeldung:
 unsupported operand type(s) for +: 'NoneType' and 'int'</code></pre>
</div>
</div>
<p>Eine Ausnahme ist die Umwandlung in eine Zeichenkette.</p>
<div id="c8ebbc54" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Eine Ausnahme ist die Umwandlung in strings</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>a <span class="op">=</span> <span class="va">None</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">print(a) gibt den Nullwert zurück:</span><span class="ch">\n</span><span class="st">"</span>, a, sep <span class="op">=</span> <span class="st">""</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">str(a) gibt eine Zeichenkette zurück:"</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="bu">str</span>(a)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
print(a) gibt den Nullwert zurück:
None

str(a) gibt eine Zeichenkette zurück:</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="91">
<pre><code>'None'</code></pre>
</div>
</div>
<p><strong>Strategien der Fehlersuche und -bereinigung: Variablen mit Datentyp Zeichenkette (oder die als solche eingelesen werden) nach “None” durchsuchen.</strong></p>
</section>
<section id="nan" class="level4">
<h4 class="anchored" data-anchor-id="nan">NaN</h4>
<p>Um mit fehlenden Werten innerhalb eines Datensatzes arbeiten zu können, gibt es den Wert <code>NaN</code>, der zur Klasse der Fließkommazahlen gehört. <code>NaN</code> steht für Not a Number und repräsentiert undefinierte oder nicht darstellbare Werte. Beispielsweise berechnet die Methode <code>pd.diff()</code> die Differenz jedes Werts zu seinem Vorgänger. Da der erste Wert keinen Vorgänger hat, wird <code>NaN</code> erzeugt.</p>
<div id="36956dec" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>my_series <span class="op">=</span> pd.Series([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">8</span>])</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>my_series.diff()</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="92">
<pre><code>0    NaN
1    1.0
2    2.0
3    4.0
dtype: float64</code></pre>
</div>
</div>
<p>Anders als <code>None</code> ist <code>NaN</code> kein Standardschlüsselwort in Python. Der Wert <code>NaN</code> wird erzeugt mit <code>float('nan')</code> oder <code>float('NaN')</code>, die Groß- und Kleinschreibung spielt keine Rolle. Die Module math und NumPy bieten mit <code>math.nan</code> und <code>np.nan</code> ebenfalls Funktionen, um <code>NaN</code> zu erzeugen.</p>
<div id="de347cfd" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>test <span class="op">=</span> <span class="bu">float</span>(<span class="st">'NaN'</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(test))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'float'&gt;</code></pre>
</div>
</div>
<p>Mit dem Wert ‘NaN’ können Operationen ausgeführt werden. Das Ergebnis ist <code>NaN</code>.</p>
<div id="7f8bb208" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(my_plusone(<span class="bu">float</span>(<span class="st">'NaN'</span>)))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>nan</code></pre>
</div>
</div>
<p>Als Platzhalter für fehlende Werte beeinträchtigt <code>NaN</code> Berechnungen nicht.</p>
<div id="4748d836" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>daten_mit_nan <span class="op">=</span> pd.Series([<span class="dv">1</span>, <span class="dv">2</span>, <span class="bu">float</span>(<span class="st">'NaN'</span>), <span class="dv">4</span>])</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_mit_nan <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Summe des Datensates:"</span>, daten_mit_nan.<span class="bu">sum</span>())</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    2.0
1    3.0
2    NaN
3    5.0
dtype: float64

Summe des Datensates: 7.0</code></pre>
</div>
</div>
<div id="wrn-logicbasepython" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;3: Achtung Logik!
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Die logische Abfrage fehlender Werte unterscheidet sich für <code>None</code> und <code>NaN</code>.</p>
<div id="f8b76da2" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="bu">bool</span>(<span class="va">None</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="96">
<pre><code>False</code></pre>
</div>
</div>
<div id="40698501" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="bu">bool</span>(<span class="bu">float</span>(<span class="st">'NaN'</span>))</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="97">
<pre><code>True</code></pre>
</div>
</div>
<div id="762c869e" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="va">None</span> <span class="op">==</span> <span class="va">None</span></span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="98">
<pre><code>True</code></pre>
</div>
</div>
<div id="8c81ebe3" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="bu">float</span>(<span class="st">'NaN'</span>) <span class="op">==</span> <span class="bu">float</span>(<span class="st">'NaN'</span>)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="99">
<pre><code>False</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="fehlende-werte-in-der-praxis" class="level3">
<h3 class="anchored" data-anchor-id="fehlende-werte-in-der-praxis">Fehlende Werte in der Praxis</h3>
<p><code>None</code> und <code>NaN</code> sind pythonspezifische Repräsentationen für nicht existente oder nicht definierte Werte. In der Praxis werden fehlende Werte in Datensätzen auf unterschiedliche Weise gekennzeichnet.</p>
<p>In Datensätzen übliche Werte sind:</p>
<ul>
<li><p>kein Eintrag, beispielsweise in kommaseparierten Dateien eine leere Zeichenkette <code>""</code></p></li>
<li><p>definierte Zeichenfolge: <code>NA</code> (in der Programmiersprache R), <code>NULL</code> (in der Datenbanksprache SQL), <code>.</code> (in der Statistik-Software Stata)</p></li>
<li><p>(mehrere) manuell gewählte Zeichen oder Ziffern außerhalb des zulässigen Wertebereichs wie -1, -88, -99 (häufig bei Umfragedaten)</p></li>
</ul>
<p>Die Art der Kennzeichnung ist jeweils mit Vor- und Nachtteilen verbunden. Eine definierte Zeichenfolge für fehlende Werte hilft dabei, Lücken im Datensatz von Fehlern bei der Datenerfassung zu unterscheiden. Dazu ist eine definierte Zeichenfolge wie “NA” besser als eine leere Zeichenkette geeignet, führt aber auch leicht dazu, dass ein numerischer Datensatz als Zeichenkette erkannt wird. Manuell gewählte Werte erlauben es, bei der automatischen Auswertung eines Datensatzes abhängig von der Situation ein bestimmtes Verhalten für jede Variable festzulegen (z. B. Unterscheidung von nicht zutreffend, Aussage verweigert, weiß nicht, Interview abgebrochen keine Antwort).</p>
<p><strong>Fehlersuche und -bereinigung: Man sollte sich über die im Dateiformat gängige Kennzeichnung fehlender Werte bewusstsein bzw. sich informieren. Hilfreich ist außerdem die Kenntnis disziplinärer Konventionen.</strong></p>
</section>
</section>
<section id="sec-metadaten" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-metadaten"><span class="header-section-number">4.4</span> Metadaten</h2>
<p>Metadaten sind beschreibende Informationen eines Datensatzes. Metadaten geben beispielsweise an:</p>
<ul>
<li><p>welche Datentypen ein Datensatz enthält,</p></li>
<li><p>verwendete Kodierschemen, Skalen oder mimimal und maximal zulässige Werte,</p></li>
<li><p>die Bedingungen, unter denen die Daten erhoben wurden,</p></li>
<li><p>Herkunft der Daten,</p></li>
<li><p>Beziehungen zwischen Variablen und Datensätzen,</p></li>
<li><p>urheberrechtliche Informationen und Lizenzhinweise.</p></li>
</ul>
<p>(vgl. <a href="https://docs.hdfgroup.org/archive/support/HDF5/doc/Advanced/HDF5_Metadata/index.html">The HDF Group Help Desk</a>)</p>
<p>Spezialisierte Dateiformate wie netCDF oder HDF deklarieren Metadaten explizit in dafür vorgesehenen Feldern. Vielen Dateiformaten fehlt eine solche Funktion. Relevante Metadaten stehen deshalb häufig im Dateinamen (<strong>Beispiel: SMARD-Daten</strong>), in Spaltenbeschriftungen (<strong>Beispiel: Zeitzone im österreichischen Strommarktdatensatz</strong>), in zusätzlichen Tabellenblättern (<strong>Beispiel besorgen</strong>) oder in separaten Dokumenten (die nicht immer zur Verfügung stehen) <strong>Koske et al.&nbsp;aus der Diss</strong>.</p>
<p><strong>Fehlersuche und -vermeidung: Datensätze und, sofern vorhanden Begleitmaterialien, erst einmal angucken (Dateiname, ggf. Tabellenblätter und Spaltenbeschriftungen mit einem Tabellenkalkulationsprogramm kontrollieren.)</strong></p>
</section>
</section>
<section id="strukturierte-datensätze-einlesen-die-module-numpy-pandas-und-glob" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Strukturierte Datensätze einlesen: die Module NumPy, Pandas und glob</h1>
<p>Die Module NumPy und Pandas erlauben ein effizientes Arbeiten mit Datensätzen. Insbesondere das Lesen- und Schreiben von Dateien und die Verwaltung von Datentypen ist erheblich einfacher als mit der Python-Basis. Außerdem sind die vektorisierten Operationen vielfach schneller als Operationen mit Python. Das Modul Pandas basiert auf NumPy. Ob Sie mit NumPy oder mit Pandas arbeiten, hängt von dem vorliegenden Datensatz und persönlichen Präferenzen ab. In den folgenden Abschnitten werden beide Module behandelt.</p>
<p>Eine kurze Übersicht der Vor- und Nachteile:</p>
<ul>
<li><p>NumPy: n-dimensionale Array-Struktur mit Unterstützung der am häufigsten verwendeten Datentypen sowie zahlreicher numerischer Formate für spezialisierte wissenschaftliche Berechnungen (<a href="https://numpy.org/devdocs/reference/arrays.scalars.html">siehe Dokumentation</a>). Ein Array kann immer nur einen Datentyp haben und die Größe von Arrays ist unveränderlich. Dafür werden Operationen etwas schneller als in der DataFrame-Struktur von Pandas ausgeführt.<br>
<strong>Querverweis auf w-NumPy</strong></p>
<ul>
<li>Spaltennamen sind mit einem strukturierten dtype möglich (<a href="https://numpy.org/doc/stable/user/basics.io.genfromtxt.html#setting-the-names">siehe Dokumentation</a>)</li>
</ul></li>
<li><p>Pandas: 2-dimensionale DataFrame-Struktur im long- und wide-Format. DataFrames können mehrere Datentypen enthalten und die Größe von DataFrames ist veränderlich. Unterstützung von Spalten- und Indexbeschriftungen.<br>
<strong>Querverweis auf w-Pandas</strong></p>
<ul>
<li>dreidimensionale DataFrames sind mit einem Multiindex möglich –&gt; das widerspricht aber dem Konzept von Tidy Data</li>
</ul></li>
</ul>
<p><strong>ergänzen: kurze Erläuterung zum Modul glob</strong></p>
<section id="datentypen" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="datentypen"><span class="header-section-number">5.1</span> Datentypen</h2>
<p>NumPy unterstützt folgende Datentypen:</p>
<table class="table">
<thead>
<tr class="header">
<th>Datentyp NumPy-Array</th>
<th>Datentyp in Python</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>int_</td>
<td>int</td>
</tr>
<tr class="even">
<td>double</td>
<td>float</td>
</tr>
<tr class="odd">
<td>cdouble</td>
<td>complex</td>
</tr>
<tr class="even">
<td>bytes_</td>
<td>bytes</td>
</tr>
<tr class="odd">
<td>str_</td>
<td>str</td>
</tr>
<tr class="even">
<td>bool_</td>
<td>bool</td>
</tr>
<tr class="odd">
<td>datetime64</td>
<td>datetime.datetime</td>
</tr>
<tr class="even">
<td>timedelta64</td>
<td>datetime.timedelta</td>
</tr>
</tbody>
</table>
<p><a href="https://numpy.org/devdocs/reference/arrays.scalars.html">Dokumentation NumPy</a></p>
<p>In den meisten Fällen verwendet das Modul Pandas die NumPy-Datentypen. Pandas führt aber auch einige zusätzliche Datentypen ein. Eine vollständige Liste finden Sie in der <a href="https://pandas.pydata.org/docs/reference/arrays.html">Pandas Dokumentation</a>. Die wichtigsten zusätzlichen Datentypen sind:</p>
<ul>
<li><p><a href="https://pandas.pydata.org/docs/user_guide/categorical.html">Kategorie</a> <code>CategoricalDtype</code></p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html#pandas.Timestamp">Zeitzonenbewusstes Datumsformat</a> <code>DatetimeTZDtype</code></p></li>
<li><p><a href="https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html#pandas.Timedelta">Timedelta</a> um Unterschiede zwischen zwei Daten oder Uhrzeiten darzustellen (kein eigener Datentyp)</p></li>
</ul>
<p><strong>To Do: eventuell in Extrakasten erklären : Nummern und chr-Codes für die Datentypen.</strong></p>
</section>
<section id="dateien-lesen-und-schreiben" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="dateien-lesen-und-schreiben"><span class="header-section-number">5.2</span> Dateien lesen und schreiben</h2>
<p>In den Werkzeugbaustein NumPy (<strong>hier Querverweis auf w-NumPy</strong>) und Pandas (<strong>hier Querverweis auf w-Pandas</strong>) haben Sie die Funktionen zum Lesen und Schreiben von Dateien kennengelernt.</p>
<p><strong>to do: Pandas</strong></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">NumPy</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Pandas</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>In NumPy können Dateien mit der Funktion <code>np.loadtxt()</code> gelesen und mit der Funktion <code>np.savetxt()</code> geschrieben werden.</p>
<ul>
<li><p><code>np.loadtxt(fname = data.txt, delimiter = ";", skiprows= #Reihen)</code><br>
<strong>Hier könnte man noch comments = ‘#’ ergänzen - Zeichen mit dem der Beginn eines Kommentars markiert ist</strong></p></li>
<li><p><code>np.savetxt(fname = dateipfad, X = daten, header = kommentar, fmt='%5.2f')</code></p></li>
</ul>
<p><strong>Hier ergänzen: Umgang mit Kommentaren und dtype –&gt; das macht für NumPy nur zu Kontrollzwecken Sinn</strong></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>I/O-Pandas: https://pandas.pydata.org/docs/user_guide/io.html</p>
</div>
</div>
</div>
</section>
<section id="umgang-mit-fehlenden-werten" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="umgang-mit-fehlenden-werten"><span class="header-section-number">5.3</span> Umgang mit fehlenden Werten</h2>
<section id="numpy-1" class="level3">
<h3 class="anchored" data-anchor-id="numpy-1">NumPy</h3>
<p>Die NumPy-Funktion <code>np.loadtxt()</code> wird verwendet, um vollständige Datensätze einzulesen. Fehlende Werte im Datensatz können problematisch sein, da diese entweder zu Fehlermeldungen bezüglich des Datentyps führen oder übersprungen werden, sodass das NumPy-Array kürzer als der eingelesene Datensatz ist. Da NumPy-Arrays immer nur einen Datentyp und eine feste Länge haben, kann das bei der Durchführung von Operationen zu Fehlern führen.</p>
<p>Folgende Datei ist Ihnen aus dem w-NumPy bekannt.</p>
<div id="6710d5d0" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">'skript/01-daten/TC01.csv'</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>daten_ohne_fehlende_werte <span class="op">=</span> np.loadtxt(dateipfad)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Daten:"</span>, daten_ohne_fehlende_werte)</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Struktur:"</span>, daten_ohne_fehlende_werte.shape)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Daten: [20.1 20.1 20.1 ... 24.3 24.2 24.2]
Struktur: (1513,)</code></pre>
</div>
</div>
<p>Angenommen, Sie haben eine zweite Messung durchgeführt und möchten die Differenz beider Datensätze berechnen. In der zweiten Messung haben Sensorfehler zu fehlenden Werten geführt, die mit ‘–’ markiert sind. Die Funktion <code>np.loadtxt()</code> kann jedoch mit fehlenden Werten nicht umgehen und gibt eine Fehlermeldung zurück.</p>
<div id="d80c5c23" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">'skript/01-daten/TC01_double_hyphen.csv'</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  daten_double_hypen <span class="op">=</span> np.loadtxt(dateipfad)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">ValueError</span> <span class="im">as</span> error:</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"Die Eingabe führt zu der Fehlermeldung:</span><span class="ch">\n</span><span class="st">"</span>, error)</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"Daten mit fehlenden Werten '--':"</span>, daten_double_hypen) </span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Die Eingabe führt zu der Fehlermeldung:
 could not convert string '--' to float64 at row 1, column 1.</code></pre>
</div>
</div>
<section id="die-funktion-np.genfromtxt" class="level4">
<h4 class="anchored" data-anchor-id="die-funktion-np.genfromtxt">Die Funktion np.genfromtxt()</h4>
<p>Um Datensätze mit fehlenden Werten einzulesen, wird die Funktion <code>np.genfromtxt(fname, delimiter = None, missing_values = None, filling_values = None)</code> verwendet. Dieses durchläuft den Datensatz <code>fname</code> in zwei Schleifen, weshalb die Funktion langsamer als <code>np.loadtxt()</code> ist. Die erste Schleife teilt den Datensatz zeilenweise am optional übergebenen Trennzeichen <code>delimiter</code> in eine Zeichenfolge auf. Die zweite Schleife konvertiert jede Zeichenkette in den passenden Datentyp. Mit den optionalen Argumenten <code>missing_values</code> und <code>filling_values</code> können der Funktion Zeichenfolgen übergeben werden, mit der fehlende Werte markiert sind bzw. ersetzt werden sollen. <a href="https://numpy.org/doc/stable/user/basics.io.genfromtxt.html">NumPy Dokumentation</a></p>
<div id="01f424e0" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">'skript/01-daten/TC01_double_hyphen.csv'</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>daten_double_hypen <span class="op">=</span> np.genfromtxt(dateipfad, missing_values <span class="op">=</span> <span class="st">'--'</span>, filling_values <span class="op">=</span> np.nan)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Daten mit fehlenden Werten '--':"</span>, daten_double_hypen)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Struktur:"</span>, daten_double_hypen.shape)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Daten mit fehlenden Werten '--': [20.1  nan 20.1 ... 24.3 24.2 24.2]
Struktur: (1513,)</code></pre>
</div>
</div>
<p>Durch die Umwandlung fehlender Werte in NaN, sind Operationen mit gleichlangen NumPy-Arrays möglich.</p>
<div id="943150de" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>daten_differenz <span class="op">=</span> daten_ohne_fehlende_werte <span class="op">-</span> daten_double_hypen</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(daten_differenz)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[ 0. nan  0. ...  0.  0.  0.]</code></pre>
</div>
</div>
<p>Die Funktion <code>np.genfromtxt()</code> kann beliebige Zeichenketten als fehlenden Wert verarbeiten. Lediglich leere Zellen können problematisch sein, da deren Inhalt <code>'\n'</code> als Zeilentrenner verarbeitet wird. <strong>testen, ob das auch bei mehrspaltiger Datei auftritt.</strong></p>
<div id="nte-npgenfromtxt" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel&nbsp;2: Leere Zellen mit np.genfromtxt()
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Enthält eine Datei leere Zellen, können diese nicht eingelesen werden, da diese automatisch übersprungen werden.</p>
<div id="b4b88924" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datei ohne Markierung fehlender Werte</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">'skript/01-daten/TC01_empty_lines.csv'</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>daten_empty_lines <span class="op">=</span> np.genfromtxt(dateipfad, missing_values <span class="op">=</span> <span class="st">''</span>, filling_values <span class="op">=</span> np.nan) </span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Daten mit fehlenden Werten '':"</span>, daten_empty_lines)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Struktur:"</span>, daten_empty_lines.shape)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Daten mit fehlenden Werten '': [20.1 20.1 20.1 ... 24.3 24.2 24.2]
Struktur: (1511,)</code></pre>
</div>
</div>
<p>Das Array ist zwei Elemente kürzer. Die Subtraktion von einem längeren NumPy-Array scheitert mit einer Fehlemeldung.</p>
<div id="1480ba27" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  result <span class="op">=</span> daten_ohne_fehlende_werte <span class="op">-</span> daten_empty_lines</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">ValueError</span> <span class="im">as</span> error:</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">"Die Eingabe führt zu der Fehlermeldung:</span><span class="ch">\n</span><span class="st">"</span>, error)</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(result)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Die Eingabe führt zu der Fehlermeldung:
 operands could not be broadcast together with shapes (1513,) (1511,) </code></pre>
</div>
</div>
<p>In diesem Fall muss auf die Stringbearbeitung aus der Python-Basis zurückgegriffen werden. Die bearbeitete Liste kann wie gewohnt mit <code>np.genfromtxt()</code> eingelesen werden.</p>
<div id="e6131ab1" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Einlesen über Datenobjekt</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>datenobjekt_empty_lines <span class="op">=</span> <span class="bu">open</span>(dateipfad, <span class="st">'r'</span>, encoding <span class="op">=</span> <span class="st">'utf-8'</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>daten_empty_lines <span class="op">=</span> datenobjekt_empty_lines.readlines()</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>datenobjekt_empty_lines.close()</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Das ausgelesene Datenobjekt (Ausschnitt):</span><span class="ch">\n</span><span class="st">"</span>, daten_empty_lines[<span class="dv">0</span>:<span class="dv">10</span>])</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Stringbearbeitung mit replace('\n', '')</span></span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(daten_empty_lines)):</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> daten_empty_lines[i] <span class="op">==</span> <span class="st">'</span><span class="ch">\n</span><span class="st">'</span>:</span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>    daten_empty_lines[i] <span class="op">=</span> <span class="st">'platzhalter'</span></span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>    daten_empty_lines[i] <span class="op">=</span> daten_empty_lines[i].replace(<span class="st">'</span><span class="ch">\n</span><span class="st">'</span>, <span class="st">''</span>)</span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Nach der Stringbearbeitung (Ausschnitt):</span><span class="ch">\n</span><span class="st">"</span>, daten_empty_lines[<span class="dv">0</span>:<span class="dv">10</span>])</span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Einlesen mit np.genfromtxt</span></span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>daten_empty_lines <span class="op">=</span> np.genfromtxt(daten_empty_lines, missing_values <span class="op">=</span> <span class="st">'platzhalter'</span>, filling_values <span class="op">=</span> np.nan)</span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Daten mit fehlenden Werten '':"</span>, daten_empty_lines)</span>
<span id="cb89-21"><a href="#cb89-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Struktur:"</span>, daten_empty_lines.shape)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Das ausgelesene Datenobjekt (Ausschnitt):
 ['# Temperatur in C\n', '20.1\n', '\n', '20.1\n', '20.1\n', '20.1\n', '\n', '20.1\n', '20.1\n', '20.1\n']

Nach der Stringbearbeitung (Ausschnitt):
 ['# Temperatur in C', '20.1', 'platzhalter', '20.1', '20.1', '20.1', 'platzhalter', '20.1', '20.1', '20.1']

Daten mit fehlenden Werten '': [20.1  nan 20.1 ... 24.3 24.2 24.2]
Struktur: (1513,)</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="fehlende-werte-in-numpy-erzeugen-prüfen-finden-ersetzen-löschen" class="level4">
<h4 class="anchored" data-anchor-id="fehlende-werte-in-numpy-erzeugen-prüfen-finden-ersetzen-löschen">Fehlende Werte in NumPy erzeugen, prüfen, finden, ersetzen, löschen</h4>
<p>Das Modul NumPy bietet Funktionen, um mit fehlenden Werten zu arbeiten.</p>
<ul>
<li><p><code>np.nan</code> erzeugt einen fehlenden Wert.</p></li>
<li><p><code>np.isnan()</code> prüft auf einen fehlenden Wert und gibt einen Wahrheitswert bzw. ein NumPy-Array mit dtype = bool zurück.</p></li>
<li><p><code>np.nonzero(np.isnan(array))</code> gibt ein eindimensionales Array mit den Indexpositionen der Elemente mit dem Wert ‘NaN’ zurück.</p></li>
<li><p><code>nan_to_num(x = array, nan = 0.0)</code> ersetzt im Array x <code>NaN</code> durch den Wert 0.0 oder durch den im Argument nan übergebenen Wert. (Hinweis: <code>nan_to_num()</code> ersetzt standardmäßig auch np.inf durch große sowie -np.inf durch große negative Zahlen.)</p></li>
<li><p><code>np.delete(arr = array, obj)</code> gibt ein neues (kürzeres) Array ohne die im Parameter obj spezifizierten Array-Bereiche zurück. Alle Elemente mit dem Wert <code>NaN</code> werden so gelöscht: <code>np.delete(array, obj = np.nonzero(np.isnan(array)))</code><br>
<strong>Hier Hinweis auf masked arrays: “Often it is preferable to use a boolean mask” <a href="https://numpy.org/doc/stable/reference/generated/numpy.delete.html">NumPy Dokumentation</a></strong><br>
<strong>“Masked arrays are arrays that may have missing or invalid entries. The numpy.ma module provides a nearly work-alike replacement for numpy that supports data arrays with masks.” <a href="https://numpy.org/doc/stable/reference/maskedarray.html">NumPy Dokumentation</a></strong></p></li>
</ul>
<p>NumPy wandelt <code>None</code> nicht automatisch in <code>NaN</code> um. NumPy kann den Datentyp des Objekts deshalb nicht bestimmen und gibt <code>dtype=object</code> aus <strong>stimmt das immer?</strong>:</p>
<div id="14f48707" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>np_array_with_none <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="va">None</span>, <span class="dv">4</span>])</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np_array_with_none)</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1 2 None 4]</code></pre>
</div>
</div>
<p><strong>Aber wie löst man das?</strong></p>
<p><strong>Kleine Aufgabe zwischendurch: Die Funktion <code>np.argwhere(np.array == np.nan)</code> soll die Indizes der Elemente zurückgeben, die den Wert np.nan haben. Warum ist die Liste immer leer?</strong></p>
</section>
<section id="funktionen-mit-fehlenden-werten" class="level4">
<h4 class="anchored" data-anchor-id="funktionen-mit-fehlenden-werten">Funktionen mit fehlenden Werten</h4>
<p>hierhier Problem: Operationen mit NaN sind immer NaN.</p>
<pre><code>nansum()
nanmax()
nanmin()
nanargmax()
nanargmin()</code></pre>
<div id="tip-argwhere" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;8: Antwort
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die logische Abfrage np.nan == np.nan ist immer False - siehe <a href="#wrn-logicbasepython" class="quarto-xref">Hinweis&nbsp;3</a>.</p>
<p>Eine Möglichkeit wäre: <code>np.argwhere(np.isnan(array))</code>, das die Indexposition der Elemente mit dem Wert <code>np.nan</code> zurückgibt. Allerdings ist der Output der Funktion nicht direkt geeignet, um damit Arraybereiche auszuwählen. Die Funktion gibt ein zweidimensionales Array der Form (N, array.ndim) zurück. N ist die Anzahl der Werte, die nicht Null sind und array.ndim die Anzahl der Dimensionen des Eingabe-Arrays.</p>
</div>
</div>
</div>
</section>
<section id="fehlende-werte-in-numpy-maskieren" class="level4">
<h4 class="anchored" data-anchor-id="fehlende-werte-in-numpy-maskieren">Fehlende Werte in NumPy maskieren</h4>
<p><a href="https://numpy.org/doc/stable/reference/maskedarray.html" class="uri">https://numpy.org/doc/stable/reference/maskedarray.html</a></p>
<p>… können auch mit genfromtxt erzeugt werden <code>usemask</code> We may also want to keep track of the occurrence of missing data by constructing a boolean mask, with True entries where data was missing and False otherwise. To do that, we just have to set the optional argument usemask to True (the default is False). The output array will then be a MaskedArray.</p>
</section>
</section>
<section id="zugriff-auf-mehrere-lokale-dateien-modul-glob" class="level3">
<h3 class="anchored" data-anchor-id="zugriff-auf-mehrere-lokale-dateien-modul-glob">Zugriff auf mehrere lokale Dateien: Modul glob</h3>
<p>Das Modul glob</p>
</section>
</section>
<section id="datentypen-erkennen-und-festlegen" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="datentypen-erkennen-und-festlegen"><span class="header-section-number">5.4</span> Datentypen erkennen und festlegen</h2>
<section id="numpy-2" class="level3">
<h3 class="anchored" data-anchor-id="numpy-2">NumPy</h3>
</section>
<section id="pandas-1" class="level3">
<h3 class="anchored" data-anchor-id="pandas-1">Pandas</h3>
</section>
</section>
</section>
<section id="datensätze-organisieren" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Datensätze organisieren</h1>
<p>In diesem Abschnitt werden typische Herausforderungen beim Einlesen strukturierter Datensätze behandelt und Werkzeuge aus den Modulen NumPy und Pandas vorgestellen, um Probleme zu identifizieren und zu beheben. Dazu wird einführend mit tidy data ein grundlegendes Konzept zur Organisation von Datensätzen vorgestellt.</p>
<section id="tidy-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="tidy-data"><span class="header-section-number">6.1</span> Tidy data</h2>
<p><strong>Konzept als Einführung gedacht: Was ist überhaupt das Ziel des Einlesens? (ist aber inkompatibel mit dem Multiindex in Python [und den fehlenden Spaltenbeschriftungen in Numpy])</strong></p>
<div>

</div>
<div class="border quarto-layout-panel" data-layout="[5, 90, 5]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“Tidy datasets are all alike, but every messy dataset is messy in its own way.” <span class="citation" data-cites="R-for-Data-Science">(<a href="#ref-R-for-Data-Science" role="doc-biblioref">Wickham, Çetinkaya-Rundel, und Grolemund 2023, Kap. 5</a> Data tidying)</span></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
</div>
<p>Tidy data ist ein System von Hadley Wickham, das dabei hilft, Datensätze in ein aufgeräumtes (tidy) Format zu bringen. Das Aufräumen von Datensätzen ist eine vorbereitende Tätigkeit mit dem Ziel, während der eigentlichen Datenanlyse möglichst wenig Zeit für das Umformen von Datenstrukturen aufwenden zu müssen. Dadurch soll ein größerer Fokus auf den inhaltlichen Aspekt der Datenanalyse ermöglicht werden. <span class="citation" data-cites="R-for-Data-Science">(<a href="#ref-R-for-Data-Science" role="doc-biblioref">Wickham, Çetinkaya-Rundel, und Grolemund 2023, Kap. 5</a> Data tidying)</span></p>
<div id="imp-tidy-data" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition&nbsp;2: tidy data
</div>
</div>
<div class="callout-body-container callout-body">
<div class="border">
<p>Das System tidy data besteht aus drei Regeln:</p>
<ol type="1">
<li><p>Jede Variable ist eine Spalte; jede Spalte ist eine Variabe.</p></li>
<li><p>Jede Beobachtung ist eine Zeile; jede Zeile ist eine Beobachtung.</p></li>
<li><p>Jeder Wert ist eine Zelle; jede Zelle ist ein einzelner Wert.</p></li>
</ol>
<p><span class="citation" data-cites="R-for-Data-Science">(<a href="#ref-R-for-Data-Science" role="doc-biblioref">Wickham, Çetinkaya-Rundel, und Grolemund 2023, Kap. 5</a> Data tidying)</span></p>
</div>
</div>
</div>
<p>Tidy data bezieht sich auf zweidimensionale Datensätze, bietet aber auch darüber hinaus eine Orientierung, um unterschiedlich aufgebaute Datensätze strukturiert einzulesen und für die Datenanalyse vorzubereiten. Tidy data ist kein strikt zu befolgendes Regelwerk. Wenn die Datenanalyse mit einer anderen Struktur leichter durchgeführt werden kann, dann ist das in Ordnung.</p>
</section>
<section id="das-modul-pandas" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="das-modul-pandas"><span class="header-section-number">6.2</span> Das Modul Pandas</h2>
<p>Das Modul Pandas bietet die DataFrame-Struktur und kann unterschiedliche Datentypen verwalten. Mit diesem Modul werden typische Probleme illustriert und Strategien der Fehlersuche und -behebung vorgestellt. Pandas.DataFrame: Vielzahl von Datentypen numerisch, character, category, boolean, datetime usw. … –&gt; hier reicht ein Querverweis auf den w-Pandas</p>
<section id="in-pandas" class="level3">
<h3 class="anchored" data-anchor-id="in-pandas">in Pandas</h3>
<p>Datentypen prüfen geht mit Pandas ziemlich einfach:</p>
<p>pandas.describe() pandas.info() [ist das aus Pandas?] pandas.dtypes() pandas.columns()</p>
<p>df.count() # count of non-missing values in each column df.count(axis=‘columns’) # count of non-missing values in each row</p>
<p>You can use methods like pd.isnull(), pd.dropna(), and pd.fillna() to detect, remove, and replace missing values.</p>
<p><strong>Mit Pandas den Datensatz messung1 einlesen, und Datum korrekt identifizieren. –&gt; besser die SMART-Datensätze nehmen, die gibt es in Deutsch und Englisch mit entsprechendem Datumsformat - siehe Material</strong></p>
<p>Das Modul Pandas wandelt None automatisch in NaN um. Als Datentyp des Objekts wird deshalb Fließkommazahl erkannt:</p>
<div id="a88ab9b8" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>pd_series_with_none <span class="op">=</span> pd.Series([<span class="dv">1</span>, <span class="dv">2</span>, <span class="va">None</span>, <span class="dv">4</span>])</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>pd_series_with_none</span></code><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="108">
<pre><code>0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64</code></pre>
</div>
</div>
<p><strong>Hinweis: <code>dtype=object</code> erscheint immer, wenn der Datentyp nicht zugeordnet werden kann. type(object) ist etwas anderes als object.dtype. Erstes bestimmt den Objekttyp, zum Beispiel Liste oder Numpy-Array. Zweiteres bestimmt den Datentyp (Ganzzahl, String). Ich glaube, <code>dtype=object</code> ist eine Liste von Zeigern auf Objekte im Speicher.</strong></p>
</section>
</section>
</section>
<section id="datumsformat" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Datumsformat</h1>
<p>Welches Datum ist heute? Das hängt vom Kalender ab: Gregorianischer Kalender in Europa, jüdischer Kalender in Israel, islamischer Kalender, Suriyakati-Kalender in Thailand (hatte ich in der Diss), Astronomische Zählweise (NumPy)</p>
<p>Unterschied NumPy und Python wird hier erklärt: https://numpy.org/doc/stable/reference/arrays.datetime.html</p>
<p>naive und aware time (aware kennt Zeitzonen, naive nicht): https://numpy.org/doc/stable/reference/arrays.datetime.html#datetime64-conventions-and-assumptions</p>
<p><strong>Fehlersuche und -bereinigung: Kalender prüfen</strong></p>
<p>Asien unterschiedlich. Ohne Kalender keine Angabe des Datums möglich.</p>
</section>
<section id="räumliche-daten" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Räumliche Daten</h1>
<p>netCDF mit eigenem Namensschema: dimensions (Name, Datentyp und Länge der Variablen), data variables (die eigentlichen Datensätze), attributes (Informationen über die Daten).</p>
</section>
<section id="strategien-der-fehlersuche-und-bereinigung" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Strategien der Fehlersuche und Bereinigung</h1>
<div>

</div>
<div class="border quarto-layout-panel" data-layout="[[5, 90, 5], [1], [1]]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“everybody I know has war stories about cleaning up lousy datasets”<br>
Nicholas J. Cox</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Cox, Nicholas J. 2004: Exploratory Data Mining and Data Cleaning. Book Review 9. In: Journal of Statistical Software 2004, Volume 11. <a href="https://www.jstatsoft.org/article/view/v011b09/30" class="uri">https://www.jstatsoft.org/article/view/v011b09/30</a></p>
</div>
</div>
</div>
<p>Inhalt (gerne abwechslungsreich gestalten)</p>
<ul>
<li><p>Theorie</p></li>
<li><p>Beispiele</p></li>
<li><p>Übungen</p></li>
</ul>
</section>
<section id="das-wichtigste-vielleicht-als-video" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Das Wichtigste (vielleicht als Video)</h1>
</section>
<section id="lernzielkontrolle" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Lernzielkontrolle</h1>
<ul>
<li><p>Kompetenzquiz (ggf. aufklappbarer Callout Block, Textverweis für PDF, polierte Lösungen evntl. via Lumi später entscheiden)</p></li>
<li><p>Übungsaufgaben (kleine Projekte)</p></li>
<li><p>Prüfungsaufgaben (ohne Lösungen)</p></li>
</ul>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Literatur</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Arnold-2023-funktionen-module-dateien" class="csl-entry" role="listitem">
Arnold, Simone. 2023a. <span>„Datenanalyse mit Python. Funktionen Module Dateien.“</span> Fachhochschule Dortmund.
</div>
<div id="ref-Arnold-2023-numpy-dateien" class="csl-entry" role="listitem">
———. 2023b. <span>„Datenanalyse mit Python. NumPy und Dateien.“</span> Fachhochschule Dortmund.
</div>
<div id="ref-Dasu-Johnson-2003" class="csl-entry" role="listitem">
Dasu, Tamraparni, und Theodore Johnson. 2003. <span>„Exploratory Data Mining and Data Cleaning“</span>. Hoboken; New Jersey.: John Wiley &amp; Sons, Inc. 2003. <a href="https://download.e-bookshelf.de/download/0000/5837/88/L-G-0000583788-0002360584.pdf">https://download.e-bookshelf.de/download/0000/5837/88/L-G-0000583788-0002360584.pdf</a>.
</div>
<div id="ref-Wickham-2014" class="csl-entry" role="listitem">
Wickham, Hadley. 2014. <span>„Tidy Data“</span>. Journal of Statistical Software. 2014. <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>.
</div>
<div id="ref-R-for-Data-Science" class="csl-entry" role="listitem">
Wickham, Hadley, Mine Çetinkaya-Rundel, und Garrett Grolemund. 2023. <span>„R for data science: Import, tidy, transform, visualize, and model data“</span>. Beijing; Boston; Farnham; Sebastopol; Tokyo: O’Reilly. 2023. <a href="https://r4ds.hadley.nz/">https://r4ds.hadley.nz/</a>.
</div>
<div id="ref-Ziemann-2016" class="csl-entry" role="listitem">
Ziemann, Mark, Yotam Eren, und Assam El-Osta. 2016. <span>„Gene name errors are widespread in the scientific literature“</span>. <em>Genome Biol.</em> 17 (1).
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>