<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Grundlagen: Merkmale von Datensätzen – Bausteine Computergestützter Datenanalyse</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../skript/datentypoperationen.html" rel="next">
<link href="../skript/einleitung.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-41d1ed59529443dc312b46011c211845.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<link rel="shortcut icon" href="skript/00-bilder/favicon_bcd_new.svg">
<link rel="icon" type="image/x-icon" href="logo.ico">


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../skript/grundlagen.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grundlagen: Merkmale von Datensätzen</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../skript/00-bilder/logo_with_text_new.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Methodenbaustein: Einlesen strukturierter Datensätze</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodenbaustein Einlesen strukturierter Datensätze</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/grundlagen.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grundlagen: Merkmale von Datensätzen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/datentypoperationen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Datentypabhängige Operationen und Funktionen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/numpy-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Die Module NumPy und Pandas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/zeitreihen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Zeitreihen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/marktdaten-oesterreich.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Markttransparenzdaten Österreich herunterladen</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/modul-glob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Zugriff auf mehrere lokale Dateien: Modul glob</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/maskierte-arrays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Maskierte Arrays</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/dateiformate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Wissenschaftliche Dateiformate</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/daswichtigste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Das Wichtigste</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../skript/lernzielkontrolle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Lernzielkontrolle</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#technisches-format" id="toc-technisches-format" class="nav-link active" data-scroll-target="#technisches-format"><span class="header-section-number">2.1</span> Technisches Format</a></li>
  <li><a href="#struktur" id="toc-struktur" class="nav-link" data-scroll-target="#struktur"><span class="header-section-number">2.2</span> Struktur</a>
  <ul class="collapse">
  <li><a href="#eindimensionale-datensätze" id="toc-eindimensionale-datensätze" class="nav-link" data-scroll-target="#eindimensionale-datensätze">Eindimensionale Datensätze</a></li>
  <li><a href="#eindimensionale-daten-einlesen-mit-python" id="toc-eindimensionale-daten-einlesen-mit-python" class="nav-link" data-scroll-target="#eindimensionale-daten-einlesen-mit-python">Eindimensionale Daten einlesen mit Python</a></li>
  <li><a href="#zweidimensionale-datensätze" id="toc-zweidimensionale-datensätze" class="nav-link" data-scroll-target="#zweidimensionale-datensätze">Zweidimensionale Datensätze</a></li>
  <li><a href="#long--und-wide-format" id="toc-long--und-wide-format" class="nav-link" data-scroll-target="#long--und-wide-format">long- und wide-Format</a></li>
  <li><a href="#übung-zweidimensionale-datensätze" id="toc-übung-zweidimensionale-datensätze" class="nav-link" data-scroll-target="#übung-zweidimensionale-datensätze">Übung zweidimensionale Datensätze</a></li>
  <li><a href="#drei--und-mehrdimensionale-datensätze" id="toc-drei--und-mehrdimensionale-datensätze" class="nav-link" data-scroll-target="#drei--und-mehrdimensionale-datensätze">Drei- und mehrdimensionale Datensätze</a></li>
  <li><a href="#übung-dreidimensionale-datensätze" id="toc-übung-dreidimensionale-datensätze" class="nav-link" data-scroll-target="#übung-dreidimensionale-datensätze">Übung dreidimensionale Datensätze</a></li>
  </ul></li>
  <li><a href="#sec-datentyp" id="toc-sec-datentyp" class="nav-link" data-scroll-target="#sec-datentyp"><span class="header-section-number">2.3</span> Datentyp</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Grundlagen: Merkmale von Datensätzen</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Bevor wir uns mit den praktischen Herausforderungen des Einlesens strukturierter Datensätze beschäftigten, werden zunächst einige Merkmale von Datensätzen behandelt, um ein grundlegendes Verständnis der Begrifflichkeiten zu schaffen und den Umgang der in der Basis von Python enthaltenen Werkzeuge zu vermitteln. Am Ende dieses Kapitels wird mit tidy data ein grundlegendes Konzept zur Organisation von Datensätzen vorgestellt.</p>
<div id="imp-Datensatz" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition&nbsp;2.1: Datensatz
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ein Datensatz ist eine Sammlung zusammengehöriger Daten. Datensätze enthalten einer oder mehreren Variablen zugeordnete Werte. Jeder Datensatz besitzt ein technisches Format, eine Struktur, mindestens eine Variable und mindestens einen Wert.</p>
</div>
</div>
<section id="technisches-format" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="technisches-format"><span class="header-section-number">2.1</span> Technisches Format</h2>
<p>Das technische Format eines Datensatzes gibt vor, mit welchen Mitteln Daten eingelesen, bearbeitet und gespeichert werden können. Einige Beispiele sind:</p>
<ul>
<li><p>Druckerzeugnis, z. B. Telefonbuch: manuelles Ablesen von Name und Telefonnummer, irreversible Bearbeitung per Stift</p></li>
<li><p>Lochkarte, z. B. Parkschein: Lesegerät erkennt Lochung und gewährt eine Freistunde, irreversible Bearbeitung mit Stanzgerät</p></li>
<li><p>Textdatei, z. B. Einwohnerzahl nach Bundesländern: Kann mit einer Vielzahl von Computerprogrammen wie Texteditor, Tabellenkalkulationsprogramm oder Programmierumgebung eingelesen, bearbeitet und gespeichert werden.</p></li>
<li><p>Hierarchical Data Format HDF5, z. B. räumliche Daten zur Blitzdichte: benötigt spezialisierte Programme oder Pakete</p></li>
</ul>
</section>
<section id="struktur" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="struktur"><span class="header-section-number">2.2</span> Struktur</h2>
<p>Datensätze speichern Daten in einer definierten n-dimensionalen Struktur.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/slicing_mf_mp.png" class="img-fluid figure-img" alt="Dargestellt sind von links nach rechts ein-, zwei- und dreidimensionale Blockstrukturen, die Datensätze repräsentieren. Die Teilgrafiken werden in den folgenden Abschnitten wiederverwendet und dabei auch näher beschrieben."></p>
<figcaption>n-dimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. 2024</p>
</div>
<section id="eindimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="eindimensionale-datensätze">Eindimensionale Datensätze</h3>
<p>Die einfachste Form sind eindimensionale Datensätze, die Werte einer einzigen Variablen zuordnen. Eindimensionale Datensätze mit Werten des gleichen Typs (bspw. Zahlen) werden <strong>Vektor</strong> genannt. Eindimensionale Datensätze, die unterschiedliche Datentypen enthalten können, heißen <strong>Liste</strong>. Eindimensionale Datensätze verfügen lediglich über eine Achse: den Index, über den Elemente angesprochen werden können.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/eindimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:50.0%" alt="Dargestellt ist ein in fünf Blöcke unterteilter Streifen, der einen eindimensionalen Datensatz repräsentiert. Die Blöcke sind entlang der 0. Achse von links nach rechts mit 0 bis 4 beschriftet. Von Block Null aus geht ein blauer Pfeil zu Block drei, der blau markiert ist."></p>
<figcaption>eindimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Beispiele eindimensionaler Datensätze sind ein Einkaufszettel oder die Urliste eines Würfelexperiments. Über den Index kann beispielsweise das Würfelergebnis an der Indexposition 2 ausgegeben werden.</p>
<div id="8c13b587" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>( <span class="op">*</span>( Augen <span class="op">:=</span> [<span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>] ) )</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Das Würfelergebnis an Indexposition 2 lautet: </span><span class="sc">{</span>Augen[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>6 2 1 2
Das Würfelergebnis an Indexposition 2 lautet: 1</code></pre>
</div>
</div>
</section>
<section id="eindimensionale-daten-einlesen-mit-python" class="level3">
<h3 class="anchored" data-anchor-id="eindimensionale-daten-einlesen-mit-python">Eindimensionale Daten einlesen mit Python</h3>
<p>An dieser Stelle eine kleine Wiederholung aus dem <a href="https://bausteine-der-datenanalyse.github.io/w-python/output/book/">Werkzeugbaustein Python</a>:<br>
Die Pythonbasis greift über Dateiobjekte auf Dateien zu. Die Funktionen und Methoden haben Sie im Werkzeugbaustein Python kennengelernt. Der Zugriff auf Dateien über die Pythonbasis ist eine verlässliche Rückfalloption und darüber hinaus nützlich, um die Enkodierung einer Datei zu bestimmen.</p>
<div id="tip-openundco" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.1: Kleine Wiederholung: Funktionen und Methoden der Pythonbasis
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<ul>
<li>Die Funktion <code>os.getcwd()</code> aus dem Modul os gibt das aktuelle Arbeitsverzeichnis aus, mit der Funktion <code>os.cwd(pfad)</code> kann es gewechselt werden.</li>
<li>Die Funktion <code>open(dateipfad, mode = 'r')</code> öffnet eine Datei im Lesemodus und gibt ein Dateiobjekt zurück.</li>
<li>Informationen zum Dateiobjekt können durch Ausgabe verschiedener Attribute abgerufen werden: <code>dateiobjekt.name</code>, <code>os.path.basename(dateiobjekt.name)</code>, <code>dateiobjekt.closed</code>, <code>dateiobjekt.mode</code>, <code>dateiobjekt.encoding</code></li>
<li>Das Dateiobjekt kann mit Methoden wie <code>dateiobjekt.read()</code>, <code>dateiobjekt.readline()</code>, <code>dateiobjekt.readlines()</code> oder der Funktion <code>list(dateiobjekt)</code> ausgelesen werden.</li>
<li>Die Methode <code>dateiobjekt.close()</code> schließt die Datei und gibt sie somit wieder für andere Programme frei.</li>
</ul>
</div>
</div>
</div>
<p><strong>Lesen Sie die Datei “python.txt” unter dem dateipfad “skript/01-daten/” ein.</strong></p>
<ul>
<li><p>Bestimmen Sie die Enkodierung der Datei.</p></li>
<li><p>Entfernen Sie die die erste Zeile aus dem Text und geben Sie den Text mit Python aus.</p></li>
<li><p>Wie kann der Text korrekt dargestellt werden?</p></li>
</ul>
<div id="tip-pythonbasis" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.2: Musterlösung python.txt
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="67af8516" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">"01-daten/"</span> <span class="op">+</span> <span class="st">"python.txt"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dateiobjekt <span class="op">=</span> <span class="bu">open</span>(dateipfad, mode <span class="op">=</span> <span class="st">'r'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Enkodierung der Datei bestimmen</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Die Enkodierung der Datei lautet: </span><span class="sc">{</span>dateiobjekt<span class="sc">.</span>encoding<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Text ausgeben</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>text_als_liste <span class="op">=</span> <span class="bu">list</span>(dateiobjekt)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(text_als_liste)):</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(text_als_liste[i])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Datei schließen.</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>dateiobjekt.close()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Die Enkodierung der Datei lautet: UTF-8


Python ist eine universell nutzbare, üblicherweise interpretierte, höhere Programmiersprache.[14] Sie hat den Anspruch, einen gut lesbaren, knappen Programmierstil zu fördern.[15] So werden beispielsweise Blöcke nicht durch geschweifte Klammern, sondern durch Einrückungen strukturiert. 

Python wurde mit dem Ziel größter Einfachheit und Übersichtlichkeit entworfen. Dies wird vor allem durch zwei Maßnahmen erreicht. Zum einen kommt die Sprache mit relativ wenigen Schlüsselwörtern aus.[49] Zum anderen ist die Syntax reduziert und auf Übersichtlichkeit optimiert. Dadurch lassen sich Python-basierte Skripte deutlich knapper formulieren als in anderen Sprachen.[50]

Van Rossum legte bei der Entwicklung großen Wert auf eine Standardbibliothek, die überschaubar und leicht erweiterbar ist. Dies war Ergebnis seiner schlechten Erfahrung mit der Sprache ABC, in der das Gegenteil der Fall ist.[51] Dieses Konzept ermöglicht, in Python Module aufzurufen, die in anderen Programmiersprachen geschrieben wurden, etwa um Schwächen von Python auszugleichen. Beispielsweise können für zeitkritische Teile in maschinennäheren Sprachen wie C implementierte Routinen aufgerufen werden.



Auszug aus https://de.wikipedia.org/wiki/Python_(Programmiersprache), abgerufen am 20.02.2025</code></pre>
</div>
</div>
<p>Enkodierung UTF-8 auswählen.</p>
<div id="7f9de413" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mit europäischen Sonderzeichen kompatible Enkodierung UTF-8 wählen</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dateiobjekt <span class="op">=</span> <span class="bu">open</span>(dateipfad, mode <span class="op">=</span> <span class="st">'r'</span>, encoding <span class="op">=</span> <span class="st">'utf-8'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Text ausgeben</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>text_als_liste <span class="op">=</span> <span class="bu">list</span>(dateiobjekt)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(text_als_liste)):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(text_als_liste[i])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Datei schließen.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>dateiobjekt.close()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Python ist eine universell nutzbare, üblicherweise interpretierte, höhere Programmiersprache.[14] Sie hat den Anspruch, einen gut lesbaren, knappen Programmierstil zu fördern.[15] So werden beispielsweise Blöcke nicht durch geschweifte Klammern, sondern durch Einrückungen strukturiert. 

Python wurde mit dem Ziel größter Einfachheit und Übersichtlichkeit entworfen. Dies wird vor allem durch zwei Maßnahmen erreicht. Zum einen kommt die Sprache mit relativ wenigen Schlüsselwörtern aus.[49] Zum anderen ist die Syntax reduziert und auf Übersichtlichkeit optimiert. Dadurch lassen sich Python-basierte Skripte deutlich knapper formulieren als in anderen Sprachen.[50]

Van Rossum legte bei der Entwicklung großen Wert auf eine Standardbibliothek, die überschaubar und leicht erweiterbar ist. Dies war Ergebnis seiner schlechten Erfahrung mit der Sprache ABC, in der das Gegenteil der Fall ist.[51] Dieses Konzept ermöglicht, in Python Module aufzurufen, die in anderen Programmiersprachen geschrieben wurden, etwa um Schwächen von Python auszugleichen. Beispielsweise können für zeitkritische Teile in maschinennäheren Sprachen wie C implementierte Routinen aufgerufen werden.



Auszug aus https://de.wikipedia.org/wiki/Python_(Programmiersprache), abgerufen am 20.02.2025</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="zweidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="zweidimensionale-datensätze">Zweidimensionale Datensätze</h3>
<p>Zweidimensionale Datensätze organisieren Werte in einer aus Zeilen und Spalten bestehenden <strong>Matrix</strong> oder einem <strong>Dataframe</strong>. Eine Matrix enthält nur einen Datentyp (bspw. Zahlen), ein Dataframe kann unterschiedliche Datentypen enthalten (bspw. Zahlen und Wahrheitswerte). In Python stellt das Modul Pandas die DataFrame-Struktur bereit (siehe <a href="https://bausteine-der-datenanalyse.github.io/w-pandas/output/book/">Werkzeugbaustein Pandas</a>).</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/zweidimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:45.0%" alt="Dargestellt ist ein zweidimensionaler Block, der einen zweidimensionalen Datensatz repräsentiert. Pfeile repräsentieren die zwei Achsen. Die nullte Achse entspricht der Länge (von oben nach unten) und die erste Achse der Breite des Datensatzes."></p>
<figcaption>zweidimensionaler Datensatz</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Typischerweise entspricht in zweidimensionalen Datensätzen jede Spalte einer <strong>Variablen</strong> und jede Zeile einer <strong>Beobachtung</strong>. Variablen speichern alle Werte eines Merkmals, zum Beispiel des Würfelergebnisses. Beobachtungen speichern alle Werte, die für eine Beobachtungseinheit gemessen wurden, z. B. für eine Person. <span class="citation" data-cites="Wickham-2014">(<a href="#ref-Wickham-2014" role="doc-biblioref">Wickham 2014, 3</a>)</span></p>
<div id="5fb153d5" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>messung1 <span class="op">=</span> pd.DataFrame({<span class="st">'Name'</span>: [<span class="st">'Hans'</span>, <span class="st">'Elke'</span>, <span class="st">'Jean'</span>, <span class="st">'Maya'</span>], <span class="st">'Geburtstag'</span>: [<span class="st">'26.02.'</span>, <span class="st">'14.03.'</span>, <span class="st">'30.12.'</span>, <span class="st">'07.09.'</span>], <span class="st">'Würfelfarbe'</span>: [<span class="st">'rosa'</span>, <span class="st">'rosa'</span>, <span class="st">'blau'</span>, <span class="st">'gelb'</span>], <span class="st">'Summe Augen'</span>: [<span class="dv">17</span>, <span class="dv">12</span>, <span class="dv">8</span>, <span class="dv">23</span>]})</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>messung1</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Über die Angabe der Indizes entlang der 0. (Zeilen) und der 1. Achse (Spalten) kann die Summe der gewürfelten Augen einer Person ausgegeben werden.</p>
<div id="233c610f" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Jean würfelte </span><span class="sc">{</span>messung1<span class="sc">.</span>iloc[<span class="dv">2</span>, <span class="dv">3</span>]<span class="sc">}</span><span class="ss"> Augen"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Jean würfelte 8 Augen</code></pre>
</div>
</div>
<p>Es ist aber auch möglich, zunächst eine Spalte auszuwählen und dann wie bei einem eindimensionalen Datensatz den Wert an einer Indexposition aufzurufen. Dies wird verkettete Indexierung genannt.</p>
<div id="032876a6" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Jean würfelte </span><span class="sc">{</span>messung1[<span class="st">'Summe Augen'</span>][<span class="dv">2</span>]<span class="sc">}</span><span class="ss"> Augen"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Jean würfelte 8 Augen</code></pre>
</div>
</div>
<div id="wrn-chainedassignment" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweis&nbsp;2.1: Verkettete Indexierung
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die verkettete Indexierung erzeugt in Pandas abhängig vom Kontext eine Kopie des Objekts oder greift auf den Speicherbereich des Objekts zu. Mit Pandas 3.0 wird die verkettete Indexierung nicht mehr unterstützt, das Anlegen einer Kopie wird zum Standard werden. Weitere Informationen erhalten Sie im zitierten Link.</p>
<div class="border quarto-layout-panel" data-layout="[5, 90, 5]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“Whether a copy or a reference is returned for a setting operation, may depend on the context. This is sometimes called <code>chained assignment</code> and should be avoided. See <a href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-view-versus-copy">Returning a View versus Copy</a>.”</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
</div>
<p>(<a href="https://pandas.pydata.org/docs/user_guide/indexing.html">Pandas Dokumentation</a>)</p>
</div>
</div>
</section>
<section id="long--und-wide-format" class="level3">
<h3 class="anchored" data-anchor-id="long--und-wide-format">long- und wide-Format</h3>
<p>Zweidimensionale Datensätze werden zumeist in einer aus Zeilen und Spalten bestehenden Matrix dargestellt. Den zeilenweise eingetragenen Beobachtungen werden Werte für die in den Spalten organisierten Variablen zugeordnet. Diese Art Daten darzustellen, wird wide-Format genannt: Mit jeder zusätzlich gemessenen Variablen wird der Datensatz breiter.</p>
<p>Eine andere Art Daten zu organisieren und über Daten nachzudenken, ist die Darstellung im long-Format. Einige Programme und Pakete erfordern Daten im long-Format oder profitieren zumindest davon beispielsweise bei der Erstellung von Grafiken. Schauen wir uns zunächst noch einmal den Datensatz messung1 im wide-Format an. Welche Beobachtungseinheiten gibt es? Welche Variablen wurden erhoben?</p>
<div id="d5e0724f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Vermutlich werden Sie davon ausgehen, dass die Beobachtungseinheiten Hans, Elke, Jean und Maya sind und die Variablen Geburtstag, Würfelfarbe und Summe Augen. Es ist aber auch denkbar, dass die Beobachtungseinheit Person mit 0, 1, 2 und 3 kodiert wurde (dem Zeilenindex des Datensatzes) und die Spalte Name ebenfalls eine der erhobenen Variablen ist. Ebenso könnte es nur zwei Variablen, Würfelfarbe und Summe Augen, geben, während die Spalten Name und Geburtstag die beobachteten Personen kodieren. Stellen Sie sich vor, es gäbe eine zweite Person mit dem Namen Hans. Dann könnten die Würfelergebnisse der Personen mit dem Namen Hans nur über den Geburtstag am 26.02. oder 11.11. korrekt zugeordnet werden.</p>
<div id="e06c235a" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>messung1 <span class="op">=</span> pd.DataFrame({<span class="st">'Name'</span>: [<span class="st">'Hans'</span>, <span class="st">'Elke'</span>, <span class="st">'Jean'</span>, <span class="st">'Maya'</span>, <span class="st">'Hans'</span>], <span class="st">'Geburtstag'</span>: [<span class="st">'26.02.'</span>, <span class="st">'14.03.'</span>, <span class="st">'30.12.'</span>, <span class="st">'07.09.'</span>, <span class="st">'11.11.'</span>], <span class="st">'Würfelfarbe'</span>: [<span class="st">'rosa'</span>, <span class="st">'rosa'</span>, <span class="st">'blau'</span>, <span class="st">'gelb'</span>, <span class="st">'rosa'</span>], <span class="st">'Summe Augen'</span>: [<span class="dv">12</span>, <span class="dv">17</span>, <span class="dv">8</span>, <span class="dv">23</span>, <span class="dv">7</span>]})</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>messung1</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Hans</td>
<td>11.11.</td>
<td>rosa</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Das long-Format macht diese Überlegungen explizit, indem identifizierende Variablen (identification variables, kurz: id vars) und gemessene Variablen (measure variables oder value vars) unterschieden werden. Die Transformation eines Datensatzes aus dem wide-Format ins long-Format wird melting (schmelzen) genannt. Das Modul Pandas bietet die Funktion <code>pd.melt(frame, id_vars = None)</code>. Diese erwartet einen DataFrame. Im optionalen Argument <code>id_vars</code> wird angegeben, welche Spalten die identifizierenden Variablen sind.</p>
<div id="c6f94fdd" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>messung1_long <span class="op">=</span> pd.melt(messung1, id_vars <span class="op">=</span> [<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>messung1_long</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Hans</td>
<td>11.11.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Hans</td>
<td>26.02.</td>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Elke</td>
<td>14.03.</td>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Jean</td>
<td>30.12.</td>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Maya</td>
<td>07.09.</td>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Hans</td>
<td>11.11.</td>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Im long-Format werden die gemessenen Variablen in der Spalte variable aufgeführt und deren Wert in der Spalte value eingetragen. Mit jeder zusätzlich erhobenen Variablen wird der Datensatz länger.</p>
<p>Wenn Sie die Unterscheidung von identifizierenden und gemessenen Variablen zu Ende denken, kann der Variablenname selbst als eine identifizierende Variable für den Wert in der Spalte value aufgefasst werden. Ein Datensatz kann als eine Struktur verstanden werden, die genau eine gemessene Variable, nämlich value, und eine Anzahl identifizierender Variablen besitzt. Dies kann im long-Format wie folgt dargestellt werden.</p>
<div id="4c842c5b" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>messung1_all_id <span class="op">=</span> pd.melt(messung1, id_vars <span class="op">=</span> [<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>messung1_all_id</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In dieser Darstellung wird beispielsweise der erste Wert 12 durch Name = Hans, Geburtstag = 26.02., Würfelfarbe = rosa und variable = Summe Augen identifiziert.</p>
<div class="quarto-layout-panel" data-layout="[70, 30]">
<div class="quarto-layout-row">
<div id="ac75030f" class="cell quarto-layout-cell" data-execution_count="11" style="flex-basis: 70.0%;justify-content: center;">
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Geburtstag</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Würfelfarbe</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">0</th>
<td style="text-align: left;">Hans</td>
<td style="text-align: left;">26.02.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">1</th>
<td style="text-align: left;">Elke</td>
<td style="text-align: left;">14.03.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">2</th>
<td style="text-align: left;">Jean</td>
<td style="text-align: left;">30.12.</td>
<td style="text-align: left;">blau</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">3</th>
<td style="text-align: left;">Maya</td>
<td style="text-align: left;">07.09.</td>
<td style="text-align: left;">gelb</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">23</td>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">4</th>
<td style="text-align: left;">Hans</td>
<td style="text-align: left;">11.11.</td>
<td style="text-align: left;">rosa</td>
<td style="text-align: left;">Summe Augen</td>
<td style="text-align: left;">7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 30.0%;justify-content: center;">
<p><img src="00-bilder/5f489ffabc91dec1ec2192dc4e993e00.jpg" class="img-fluid" alt="dekoratives Bild eines staunenden Hundes"></p>
</div>
</div>
</div>
<div class="border">
<p>Much wow. Such architecture. von Dmitry Kudryavtsev ist verfügbar unter <a href="https://yieldcode.blog/post/bloat-in-software-engineering/" class="uri">https://yieldcode.blog/post/bloat-in-software-engineering/</a>.</p>
</div>
<p><strong>Was passiert, wenn auch die Variable <code>Summe Augen</code> dem Argument <code>id_vars</code> übergeben wird?</strong></p>
<div id="tip-Antwort-all-id" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.3: Antwort
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Der Befehl <code>messung1_all_id = pd.melt(messung1, id_vars = ['Name', 'Geburtstag', 'Würfelfarbe', 'Summe Augen'])</code> produziert einen leeren Dataframe, weil keine gemessenen Werte verbleiben.</p>
</div>
</div>
</div>
<p>Auch der umgekehrte Fall ist möglich: Werden beim melting keine id_vars angegeben, werden alle Spalten als gemessene Variablen behandelt.</p>
<div id="52f28977" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>messung1_no_id <span class="op">=</span> pd.melt(messung1)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>messung1_no_id</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Name</td>
<td>Hans</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Name</td>
<td>Elke</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Name</td>
<td>Jean</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Name</td>
<td>Maya</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Name</td>
<td>Hans</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Geburtstag</td>
<td>26.02.</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Geburtstag</td>
<td>14.03.</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Geburtstag</td>
<td>30.12.</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Geburtstag</td>
<td>07.09.</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Geburtstag</td>
<td>11.11.</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>&nbsp;</p>
<p>Die Umkehroperation zum melting wird casting (gießen) oder pivoting (schwenken) genannt. Dabei wird ein im long-Format vorliegender Datensatz in das wide-Format konvertiert. Die Pandas Funktion <code>pd.pivot(data, columns, index)</code> nimmt einen melted DataFrame entgegen und konveriert diesen aus den einzigartigen Werten in columns (= Spaltennamen des DataFrame im wide-Format) und den einzigartigen Werten in index (= Zeilenindex des DataFrame im wide-Format). Wird der Funktion keine Spalte für index übergeben, wird der bestehende Index des melted DataFrame verwendet (der mit 20 Zeilen natürlich viel zu lang ist.) Da das Objekt messung1_no_id keine geeignete Indexspalte besitzt, muss diese vor dem casting erzeugt werden. Dies ist mit der Methode <code>messung1_no_id.groupby('variable').cumcount()</code> möglich, die die Anzahl jeder Ausprägung in der übergebenen Spalte bei 0 beginnend durchzählt. (Ein direktes Ersetzen des Index ist auf diese Weise nicht möglich, da der Index des an <code>pd.pivot(data, columns, index)</code> übergebenen DataFrames keine Doppelungen enthalten darf.)</p>
<div id="6551942d" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pd.pivot() benötigt einen Index oder benutzt den bestehenden Index, des melted_df, der zu lang ist</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Deshalb eine zusätzliche Spalte in messung1_no_id einfügen</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co">## einfach: messung1_no_id['new_index'] = list(range(0, 5)) * 4 </span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">## allgemein: messung1_no_id['new_index'] = messung1_no_id.groupby('variable').cumcount()</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalte new_index einfügen</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>messung1_no_id[<span class="st">'new_index'</span>] <span class="op">=</span> messung1_no_id.groupby(<span class="st">'variable'</span>).cumcount()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span> (<span class="ss">f"Der Datensatz im long-Format mit zusätzlicher Spalte new_index:</span><span class="ch">\n</span><span class="sc">{</span>messung1_no_id<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># casting</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>messung1_cast <span class="op">=</span> pd.pivot(messung1_no_id, index <span class="op">=</span> <span class="st">'new_index'</span>, columns <span class="op">=</span> <span class="st">'variable'</span>, values <span class="op">=</span> <span class="st">'value'</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Der Datensatz im wide-Format:</span><span class="ch">\n</span><span class="sc">{</span>messung1_cast<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Der Datensatz im long-Format mit zusätzlicher Spalte new_index:
       variable   value  new_index
0          Name    Hans          0
1          Name    Elke          1
2          Name    Jean          2
3          Name    Maya          3
4          Name    Hans          4
5    Geburtstag  26.02.          0
6    Geburtstag  14.03.          1
7    Geburtstag  30.12.          2
8    Geburtstag  07.09.          3
9    Geburtstag  11.11.          4
10  Würfelfarbe    rosa          0
11  Würfelfarbe    rosa          1
12  Würfelfarbe    blau          2
13  Würfelfarbe    gelb          3
14  Würfelfarbe    rosa          4
15  Summe Augen      12          0
16  Summe Augen      17          1
17  Summe Augen       8          2
18  Summe Augen      23          3
19  Summe Augen       7          4

Der Datensatz im wide-Format:
variable  Geburtstag  Name Summe Augen Würfelfarbe
new_index                                         
0             26.02.  Hans          12        rosa
1             14.03.  Elke          17        rosa
2             30.12.  Jean           8        blau
3             07.09.  Maya          23        gelb
4             11.11.  Hans           7        rosa</code></pre>
</div>
</div>
<p>Das Ergebnis entspricht noch nicht dem ursprünglichen Datensatz im wide-Format. Um das Ausgangsformat wiederherzustellen, müssen die Spalten in die ursprüngliche Reihenfolge gebracht sowie der Index und dessen Beschriftung zurückgesetzt werden.</p>
<div id="bee93ba4" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalten anordnen, Index zurücksetzen</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>messung1_cast <span class="op">=</span> messung1_cast[[<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>, <span class="st">'Summe Augen'</span>]]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>messung1_cast.reset_index(drop <span class="op">=</span> <span class="va">True</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>messung1_cast.rename_axis(<span class="va">None</span>, axis <span class="op">=</span> <span class="dv">1</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Der Datensatz im wide-Format mit zurückgesetztem Index:</span><span class="ch">\n\n</span><span class="sc">{</span>messung1_cast<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Der Datensatz im wide-Format mit zurückgesetztem Index:

   Name Geburtstag Würfelfarbe Summe Augen
0  Hans     26.02.        rosa          12
1  Elke     14.03.        rosa          17
2  Jean     30.12.        blau           8
3  Maya     07.09.        gelb          23
4  Hans     11.11.        rosa           7</code></pre>
</div>
</div>
<div id="tip-idvars" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.4: identifizierende und gemessene Variablen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Auch wenn Sie mit Datensätzen im wide-Format arbeiten, ist die Unterscheidung identifizierender und gemessener Variablen nützlich, um Datensätze zu organisieren. <a href="datentypoperationen.html#sec-tidydata" class="quarto-xref">siehe&nbsp;<span>3.2</span></a></p>
</div>
</div>
</div>
</section>
<section id="übung-zweidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="übung-zweidimensionale-datensätze">Übung zweidimensionale Datensätze</h3>
<p>Oben wurde das Objekt messung1_long mit dem Befehl <code>messung1_long = pd.melt(messung1, id_vars = ['Name', 'Geburtstag'])</code> angelegt.<br>
<strong>Benutzen Sie die Funktion</strong> <code>pd.DataFrame.pivot()</code>, <strong>um den Datensatz messung1 wieder ins wide-Format zu transformieren.</strong></p>
<div id="62e2a263" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>Würfelfarbe</td>
<td>blau</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>Würfelfarbe</td>
<td>gelb</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Hans</td>
<td>11.11.</td>
<td>Würfelfarbe</td>
<td>rosa</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Hans</td>
<td>26.02.</td>
<td>Summe Augen</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Elke</td>
<td>14.03.</td>
<td>Summe Augen</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Jean</td>
<td>30.12.</td>
<td>Summe Augen</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Maya</td>
<td>07.09.</td>
<td>Summe Augen</td>
<td>23</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Hans</td>
<td>11.11.</td>
<td>Summe Augen</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="tip-pivoting" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.5: Musterlösung zweidimensionale Datensätze
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="9f244658" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalte new_index einfügen</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>messung1_long[<span class="st">'new_index'</span>] <span class="op">=</span> messung1_long.groupby(<span class="st">'variable'</span>).cumcount()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># casting</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>messung1_long_cast <span class="op">=</span> pd.pivot(messung1_long, index <span class="op">=</span> <span class="st">'new_index'</span>, columns <span class="op">=</span> <span class="st">'variable'</span>, values <span class="op">=</span> <span class="st">'value'</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Spalten anordnen, Index zurücksetzen</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>messung1_long_cast <span class="op">=</span> messung1_cast[[<span class="st">'Name'</span>, <span class="st">'Geburtstag'</span>, <span class="st">'Würfelfarbe'</span>, <span class="st">'Summe Augen'</span>]]</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>messung1_long_cast.reset_index(drop <span class="op">=</span> <span class="va">True</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>messung1_long_cast.rename_axis(<span class="va">None</span>, axis <span class="op">=</span> <span class="dv">1</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>messung1_long_cast</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Geburtstag</th>
<th data-quarto-table-cell-role="th">Würfelfarbe</th>
<th data-quarto-table-cell-role="th">Summe Augen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Hans</td>
<td>26.02.</td>
<td>rosa</td>
<td>12</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Elke</td>
<td>14.03.</td>
<td>rosa</td>
<td>17</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Jean</td>
<td>30.12.</td>
<td>blau</td>
<td>8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Maya</td>
<td>07.09.</td>
<td>gelb</td>
<td>23</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Hans</td>
<td>11.11.</td>
<td>rosa</td>
<td>7</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="drei--und-mehrdimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="drei--und-mehrdimensionale-datensätze">Drei- und mehrdimensionale Datensätze</h3>
<p>Drei- oder mehrdimensionale Datensätze organisieren komplexe Datenstrukturen in sogenannten <strong>Arrays</strong>. Arrays sind n-dimensionale Datenstrukturen und damit zugleich ein Oberbegriff. So ist eine Liste ein eindimensionales Array, eine Matrix ein zweidimensionales Array und eine Excel-Datei mit mehreren Arbeitsblättern für jährlich erhobene Umfragedaten ein 3-dimensionales Array (Arbeitsblätter, Zeilen, Spalten). Abhängig vom verwendeten Modul können Arrays ein oder mehrere Datentypen enthalten.</p>
<!-- ggf. ergänzen: Modul xarray <https://docs.xarray.dev/en/stable/user-guide/pandas.html> -->
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/dreidimensionaler-datensatz-slicing-mf-mp.png" class="img-fluid figure-img" style="width:50.0%" alt="Dargestellt ist ein dreidimensionaler Block, der einen dreidimensionalen Datensatz repräsentiert. Pfeile repräsentieren die drei Achsen. Die nullte Achse entspricht der Tiefe, die erste Achse der Länge (von oben nach unten) und die zweite Achse der Breite des Datensatzes."></p>
<figcaption>dreidimensionale Datensätze</figcaption>
</figure>
</div>
<p>slicing von Marc Fehr ist lizensiert unter <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen#CC-BY-4.0-1-ov-file">CC-BY-4.0</a> und abrufbar auf <a href="https://github.com/bausteine-der-datenanalyse/w-python-numpy-grundlagen">GitHub</a>. Die Grafik wurde auf den gezeigten Teil beschnitten und die obenstehende Beschriftung entfernt. 2024</p>
</div>
<p>&nbsp;</p>
<p>Für drei- und mehrdimensionale Datenstrukturen werden häufig spezialisierte Datenformate verwendet, die im Abschnitt <a href="dateiformate.html" class="quarto-xref"><span>Kapitel 9</span></a> behandelt werden. Dies hat unter anderem den Grund, dass so leichter verschiedene Datentypen verarbeitet und mit Metadaten (siehe <a href="datentypoperationen.html#sec-metadaten" class="quarto-xref"><span>Kapitel 3.1</span></a>) dokumentiert werden können.</p>
<section id="bilddaten-einlesen" class="level4">
<h4 class="anchored" data-anchor-id="bilddaten-einlesen">Bilddaten einlesen</h4>
<div class="border">
<p>Digitale Bilder liegen in Form eines dreidimensionalen Datensatzes vor. In Zeilen und Spalten liegen für jeden Pixel Farbwerte (Rot, Grün, Blau) und gegebenenfalls ein Alphawert vor (Rot, Grün, Blau, Alpha). Die Farbwerte liegen entweder im Bereich von 0 bis 1 oder von 0 bis 255 (8-Bit).</p>
<pre><code># Farbwerte für einen Pixel
[Rotwert, Grünwert, Blauwert]

# Eine Bildzeile mit drei Pixeln
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]]

# Ein Bild aus drei Zeilen und Spalten
[[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]],
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]],
[[Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert], [Rotwert, Grünwert, Blauwert]]]</code></pre>
<p>Bilddateien können mit der Funktion <code>plt.imread()</code> aus dem Modul <code>matplotlib.pyplot</code> eingelesen werden.</p>
<div class="border">
<div id="3e520ea4" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>logo <span class="op">=</span> plt.imread(fname <span class="op">=</span> <span class="st">'00-bilder/python-logo-and-wordmark-cc0-tm.png'</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>plt.imshow(logo)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="grundlagen_files/figure-html/cell-18-output-1.png" width="575" height="201" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Python Logo von Python Software Foundation steht unter der <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPLv3</a>. Die Wort-Bild-Marke ist markenrechtlich geschützt: <a href="https://www.python.org/psf/trademarks/" class="uri">https://www.python.org/psf/trademarks/</a>. Das Werk ist abrufbar auf <a href="https://de.m.wikipedia.org/wiki/Datei:Python_logo_and_wordmark.svg">wikimedia</a>. 2008</p>
</div>
<p>&nbsp;</p>
<p>Die Struktur des Datensatzes kann mit dem Attribut <code>.shape</code> abgerufen werden.</p>
<div id="114dc994" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(logo), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logo.shape)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'numpy.ndarray'&gt; 

(144, 486, 4)</code></pre>
</div>
</div>
<p>Die Daten wurden als NumPy.ndarray eingelesen. Das Logo hat 144 Zeilen, 486 Spalten und liegt im RGBA-Farbraum vor. Ein Ausschnitt der Daten sieht so aus:</p>
<div id="55d07626" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logo[<span class="dv">50</span>:<span class="dv">52</span>, <span class="dv">50</span>:<span class="dv">52</span>, : ])</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[[0.21568628 0.44705883 0.63529414 1.        ]
  [0.21568628 0.44705883 0.63529414 1.        ]]

 [[0.21568628 0.44705883 0.63529414 1.        ]
  [0.21176471 0.44313726 0.6313726  1.        ]]]</code></pre>
</div>
</div>
<p><span class="citation" data-cites="Arnold-2023-numpy-dateien">(<a href="#ref-Arnold-2023-numpy-dateien" role="doc-biblioref">Arnold 2023</a>)</span></p>
</div>
</section>
</section>
<section id="übung-dreidimensionale-datensätze" class="level3">
<h3 class="anchored" data-anchor-id="übung-dreidimensionale-datensätze">Übung dreidimensionale Datensätze</h3>
<p>Über den Index der dritten Dimension können die Farbkanäle Rot, Grün und Blau ausgewählt und mit der Funktion <code>plt.imshow(cmap = 'Greys_r')</code> einzeln dargestellt werden. Das Argument <code>cmap = 'Greys_r'</code> weist die Funktion an, die invertierte Grauskala benutzen. Dadurch werden hohe Farbwerte hell und niedrige Farbwerte dunkel dargestellt. <strong>Stellen Sie die Farbkanäle Rot, Grün und Blau des Pythonlogos einzeln mit der Funktion <code>plt.imshow(cmap = 'Greys_r')</code> dar.</strong></p>
<div id="tip-logo" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.7: Musterlösung dreidimensionale Datensätze
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="424dffa0" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>kanal <span class="op">=</span> [<span class="st">"Rotkanal"</span>, <span class="st">"Grünkanal"</span>, <span class="st">"Blaukanal"</span>]</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize <span class="op">=</span> (<span class="dv">9</span>, <span class="dv">6</span>))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  plt.subplot(<span class="dv">1</span>, <span class="dv">4</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  plt.imshow(logo[ :, :, i], cmap <span class="op">=</span> <span class="st">'Greys_r'</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  plt.title(label <span class="op">=</span> kanal[i])</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>plt.colorbar(shrink <span class="op">=</span> <span class="fl">0.15</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="grundlagen_files/figure-html/cell-21-output-1.png" alt="Dargestellt sind die drei Farbkanäle des Pythonlogos." width="654" height="115" class="figure-img"></p>
<figcaption>Farbkanäle des Pythonlogos</figcaption>
</figure>
</div>
</div>
</div>
<p>Möglicherweise wundern Sie sich, warum der Bildhintergrund in jedem Farbkanal schwarz ist. Die Ursache finden Sie im nächsten Tipp.</p>
<div id="tip-logo" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tipp&nbsp;2.6: Erklärung Bildhintergrund
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Der Bildhintergrund hat in allen Kanälen, auch im Alphakanal, den Farbwert 0. Dieser Teil des Bildes ist deshalb vollständig transparent und wird vom Hintergrund der Internetseite ausgefüllt. Der Bildhintergrund des Logos wirkt deshalb weiß.</p>
<div id="80c490dc" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alphakanal</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>plt.imshow(logo[ :, :, <span class="dv">3</span>], cmap <span class="op">=</span> <span class="st">'Greys_r'</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>plt.title(label <span class="op">=</span> <span class="st">'Alphakanal'</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>plt.colorbar(shrink <span class="op">=</span> <span class="fl">0.4</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Die ersten zwei Zeilen und Spalten des Logos</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(logo[<span class="dv">0</span>:<span class="dv">2</span>, <span class="dv">0</span>:<span class="dv">2</span>, : ])</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="grundlagen_files/figure-html/cell-22-output-1.png" alt="Dargestellt ist der Alphakanal des Pythonlogos. Der Bildhintergrund hat den Farbwert 0." width="535" height="185" class="figure-img"></p>
<figcaption>Alphakanal des Pythonlogos</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-datentyp" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-datentyp"><span class="header-section-number">2.3</span> Datentyp</h2>
<p>Der Datentyp gibt an, wie die in einem Datensatz einhaltenen Werte von Python interpretiert werden sollen. Beispielsweise kann der Wert “1” ein Zeichen, eine Ganzzahl, einen Wahrheitswert, den Monat Januar oder die Ausprägung einer kategorialen Variablen repräsentieren. Python unterstützt als vielseitig einsetzbare Programmiersprache zahlreiche Datentypen, die den Kategorien: numerics, sequences, mappings, classes, instances and exceptions zugeordnet sind. Nähere Informationen dazu finden Sie in der <a href="https://docs.python.org/3/library/stdtypes.html">Dokumentation</a>.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/python3-standard-type-hierarchy.png" class="img-fluid figure-img" style="width:60.0%" alt="Dargestellt ist eine Kategorisierung der Standardtypen in Python. Die Kategorisierung ist nicht vollständig deckungsgleich zu den in der Dokumentation genannten Kategorien von Datentypen. Der Typ None für Nullwerte hat keine weitere Unterteilung. Die Kategorie Numbers unterteilt sich in Zahlenwerte (Ganzzahlen, boolsche Wahrheitswerte), reele Zahlen (floats) und komplexe Zahlen. Die Kategorie Sequences unterteilt sich in Unveränderliche (Strings, Tuple, Bytes) und Veränderliche (Listen, Byte Arrays). Die Kategorie Set Types unterteilt sich in Sets (Mengen) und Frozen Sets. Die Kategorie Mappings enthält Dictionaries (Wörterbücher). Die Kategorie Callable umfasst Funktionen, Methoden und Klassen. Außerdem gibt es die Kategorie Module."></p>
<figcaption>Datentypen in Python</figcaption>
</figure>
</div>
<p>Python 3. The standard type hierarchy. von Максим Пе ist lizensiert unter <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.de">CC BY SA 4.0</a> und abrufbar auf <a href="https://commons.wikimedia.org/wiki/File:Python_3._The_standard_type_hierarchy.png">wikimedia</a>. 2018</p>
</div>
<p>&nbsp;</p>
<p>Durch Module werden weitere Datentypen hinzugefügt. In der Datenanalyse häufig verwendete Datentypen sind:</p>
<ul>
<li><p>Zahlen: Ganzzahl, Fließkommazahlen</p></li>
<li><p>Wahrheitswerte</p></li>
<li><p>Zeichenketten</p></li>
<li><p>Datums- und Uhrzeitangaben</p></li>
<li><p>Kategorie<!-- Faktor in R--> (aus dem Modul <a href="https://pandas.pydata.org/docs/user_guide/categorical.html">Pandas</a>)</p></li>
</ul>
<p>Der Datentyp bestimmt zum einen den zulässigen Wertebereich einer Variablen. Beispielsweise sind 0 und 13 zulässige Ganzzahlen, aber keine gültigen Kodierungen des Monats. Zum anderen definiert der Datentyp, welche Operationen mit den Werten zulässig sind und wie diese von Python ausgeführt werden. Dies betrifft Operatoren und Funktionen. Python enthält Funktionen, um den Datentyp eines Werts zu bestimmen und ggf. umzuwandeln (siehe w-Python).</p>
<div id="nte-operation-nach-datentyp" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beispiel&nbsp;2.1
</div>
</div>
<div class="callout-body-container callout-body">


</div>
</div>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Arnold-2023-numpy-dateien" class="csl-entry" role="listitem">
Arnold, Simone. 2023. <em>Datenanalyse mit Python. NumPy und Dateien.</em> Fachhochschule Dortmund.
</div>
<div id="ref-Wickham-2014" class="csl-entry" role="listitem">
Wickham, Hadley. 2014. <span>„Tidy Data“</span>. No. 10. Bd. 59. Journal of Statistical Software. <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../skript/einleitung.html" class="pagination-link" aria-label="Einleitung">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einleitung</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../skript/datentypoperationen.html" class="pagination-link" aria-label="Datentypabhängige Operationen und Funktionen">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Datentypabhängige Operationen und Funktionen</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>