# Zugriff auf mehrere lokale Dateien: Modul glob

``` {python}
# Vorbereitung: Module aus vorherigem Kapitel erneut laden
import numpy as np
import pandas as pd
```

::: {.border}
Das Modul [glob](https://docs.python.org/3/library/glob.html#module-glob) erlaubt es, mit der Funktion `glob.glob(pathname, *, root_dir = None, recursive = False)` aus einem Ordner alle Dateipfade, die dem im Argument `pathname` spezifizierten Muster entsprechen zurückzugeben. Das Argument `pathname` kann als Schlüsselwort oder positional übergeben werden, die übrigen Argumente müssen als Schlüsselwort übergeben werden (dies signalisiert das Zeichen `*`). Die Speicheradresse des Ordners wird mit dem Argument `root_dir` übergeben, dessen Standardwert das aktuelle Arbeitsverzeichnis ist. 
Im Argument `pathname` können Platzhalter, sogenannte Wildcards, verwendet werden, um beliebige Zeichen und Zeichenfolgen zu spezifizieren.

| Wildcard | Funktion |
| :--: | :------------: |
| `*` | beliebige Zeichenfolge außer Dateipfadelemente wie `/` oder `.` |
| `?` | genau ein beliebiges Zeichen |
|`[]` | alle in den Klammern eingeschlossenen Zeichen inklusive der Wildcards `*` `?`|
|`[0-9]` | alle Ziffern 0 bis 9 |

&nbsp;

Unter dem Pfad '01-daten/glob' liegen, teils in einem Unterordner, verschiedene Dateien.


``` {python}
import glob
ordnerpfad = '01-daten/glob' 

pfadliste = glob.glob(pathname = '*', root_dir = ordnerpfad, recursive = False)
print(pfadliste)

```

Das Argument `recursive` steuert, ob auch Unterordner durchsucht werden. Um auch Unterordner zu durchsuchen, muss es auf True gesetzt und im pathname `**` spezifiziert werden.

``` {python}
pfadliste = glob.glob(pathname = '**', root_dir = ordnerpfad, recursive = True)
print(pfadliste)

```

Im angegebenen Pfad '01-daten/glob' liegen die Dateien 'hintergrund.png', 'ToothGrowth.csv', 'Unfallorte2020_LinRef.csv', 'Unfallorte2022_LinRef.csv' sowie der Unterordner 'Unterordner glob'. In diesem Unterordner liegen die Dateien 'Unfallorte2021_LinRef.csv' und 'Unfallorte2023_LinRef.csv'.

Um die Suchergebnisse auf die Dateien 'Unfallorte2020_LinRef.csv', 'Unfallorte2021_LinRef.csv', 'Unfallorte2022_LinRef.csv' und 'Unfallorte2023_LinRef.csv' zu beschränken, muss der im Argument `pathname` übergebene Dateipfad angepasst werden.  **Schauen Sie in die [Dokumentation des Moduls glob](https://docs.python.org/3/library/glob.html#module-glob) und übergeben einen geeigneten Dateipfad.**

::: {#tip-glob .callout-tip collapse="true"}
## Tipp und Musterlösung

Tipp: Die gesuchten Dateien beginnen mit dem Buchstaben 'U' und enden mit der Dateiendung '.csv'. Wie Sie Dateien aus einem Ordner und aus einem Unterordner auslesen, sehen Sie in der verlinkten Dokumentation unter Examples. 

:::: {#tip-glob .callout-tip collapse="true"}
## Musterlösung glob

``` {python}
pfadliste = glob.glob(pathname = '**/U*.csv', root_dir = ordnerpfad, recursive = True)
print(pfadliste)

```

::::
:::

Mit den Dateipfaden können die Dateien mit Hilfe einer Schleife in eine Liste eingelesen werden (aus Gründen der Lesbarkeit jeweils 3 Zeilen und 3 Spalten).

``` {python}
list_of_files = []
for pfad in pfadliste:
  zwischenspeicher = pd.read_csv(filepath_or_buffer = ordnerpfad + '/' + pfad, 
  delimiter = ';', nrows = 3, usecols = [0, 1, 2])
  list_of_files.append(zwischenspeicher)
  print(pfad, "\n", zwischenspeicher, "\n")

```

Aus der Liste können die Datensätze dann eigenen Objekten zugewiesen werden.

``` {python}
unfalldaten2020 = list_of_files[0] 
unfalldaten2021 = list_of_files[2] 
unfalldaten2022 = list_of_files[1] 
unfalldaten2023 = list_of_files[3] 

print(unfalldaten2020, "\n")
print(unfalldaten2020.dtypes)
```

Die Objekte könnten auch in einem DataFrame zusammengeführt werden.

``` {python}
# Spalte OID_ / OBJECTID vereinheitlichen
unfalldaten = pd.concat([unfalldaten2020.iloc[: , 1:3], unfalldaten2022.iloc[: , 1:3], unfalldaten2023.iloc[: , 1:3] ], ignore_index = True)
unfalldaten.insert(loc = 0, column = 'OBJECTID', value = pd.Series(range(1, unfalldaten.shape[0] + 1)))
unfalldaten = unfalldaten.astype('uint64')

unfalldaten
```

[@Arnold-2023-funktionen-module-dateien]

:::

## Übungen Modul glob

#### Leicht: US State Facts and Figures
Im Ordner "01-daten/glob leicht" liegen verschiedene .CSV-Dateien mit Daten zu den US-Bundesstaaten. **Lesen Sie die Dateien in einen neuen Datensatz  ein.**

  - Wie heißen die Dateien?

  - Welche Regionen werden in den Datensätzen unterschieden?
  
  - Wie viele Staaten gehören zu jeder Region?
  
  - Welche Region ist flächenmäßig die größte?

::: {.border}

US State Facts and Figures von Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) The New S Language. Wadsworth & Brooks/Cole. [rdocumentation.org](https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/state). Datensätze:

  - state.abb

  - state.area

  - state.name

  - state.region

Die Datensätze können in R durch Eingabe des Datensatznamens in der Konsole aufgerufen werden.
:::

::: {#tip-musterloesung-glob .callout-tip collapse="true"}
## Musterlösung US State Facts and Figures
Mit dem Modul glob werden die Pfade der im Ordner liegenden Dateien in einer Liste gespeichert. In einer Schleife wird mit der Funktion `open()` jede Datei als Dateiobjekt geöffnet, aus dem der Dateiname und der Dateiinhalte ausgelesen werden, um diese zu betrachten.

``` {python}
import os
ordnerpfad = "01-daten/glob leicht" 
pfadliste = glob.glob(pathname = '*', root_dir = ordnerpfad, recursive = False)

list_of_files = []
names_of_files = []
for pfad in pfadliste:

  # Dateiobjekt öffnen
  zwischenspeicher = open(ordnerpfad + '/' + pfad, 'r')
  
  # Dateinamen extrahieren
  name = os.path.basename(zwischenspeicher.name)
  names_of_files.append(name)

  # Datei auslesen
  datei = zwischenspeicher.read()
  list_of_files.append(datei)

  # Ausgabe
  print(name, "Encoding:", zwischenspeicher.encoding)
  print(datei[0:40], "\n")

  # Dateiobjekt schließen
  zwischenspeicher.close()

print(f"Die Dateien heißen:\n{names_of_files}")
```

Als nächstes werden die Daten in einem Datensatz 'states' gespeichert. Als Spaltennamen bieten sich die Dateinamen ohne Dateiendung an. 

``` {python}
# Spaltennamen vorbereiten
i = 0
for name in names_of_files:
  names_of_files[i] = name[0:-4]
  i+= 1

# DataFrame erstellen
states = pd.DataFrame()
i = 0
list_of_files = []
for pfad in pfadliste:
  zwischenspeicher = open(ordnerpfad + '/' + pfad, 'r')
  states[i] = pd.read_csv(filepath_or_buffer = zwischenspeicher, sep = ' ', usecols = [1]) # skiprows = 1 überspringt den ersten Staat
  zwischenspeicher.close()
  i+= 1

# Spaltennamen eintragen
states.columns = names_of_files

print(f"Es gibt die Regionen:\n{states['state region'].unique()}\n")

states.head()
```

Im nächsten Schritt können die Anzahl der Staaten und die Fläche je Region bestimmt werden.

``` {python}
print(f"Die Anzahl der Staaten je Region beträgt:\n{states.groupby('state region')['state name'].apply(len)}\n")
print(f"Die Fläche der Regionen beträgt:\n{states.groupby('state region')['state area'].apply(sum)}\n")

```

:::

#### Schwer: DSB Unfallatlas
Im Skript wurden bereits Daten aus dem DSB Unfallatlas eingelesen. Aus Gründen der Lesbarkeit wurden jedoch nur die ersten drei Zeilen und Spalten eingelesen. Für diese Aufgabe sollen nun die Dateien im Dateipfad '01-daten/glob schwer' vollständig eingelesen und zu einem Datensatz zusammengeführt werden. Ein Problem dabei ist, dass die Spaltenbeschriftungen für den Straßenzustand und die ID-Variable nicht einheitlich sind.

::: {.border}

Unfallatlas Deutschland. von Statistische Ämter des Bundes und der Länder steht unter der Lizenz [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.de) und ist verfügbar auf dem [Statistikportal des Bundes und der Länder](https://unfallatlas.statistikportal.de/ ). 2024

:::

:::  {#tip-musterloesung-unfallatlas .callout-tip collapse="true"}
## Musterlösung Unfallatlas

Das Erhebungsjahr ist eine Variable im Datensatz. Dennoch wird gezeigt, wie dieses aus dem Dateinamen ausgelesen werden kann.

Zuerst werden der Inhalt des Ordners und anschließend die Dateipfade ausgelesen.
``` {python}
# Inhalt Ordner auslesen
ordnerpfad = '01-daten/glob schwer'
pfadliste = glob.glob(pathname = '**', root_dir = ordnerpfad, recursive = True)
print(f"Im Suchpfad liegen {len(pfadliste)} Elemente. Die Bezeichnungen lauten:\n{pfadliste}\n")

# Dateipfade auslesen
pfadliste = glob.glob(pathname = '**/U*.csv', root_dir = ordnerpfad, recursive = True)
print(f"Im Suchpfad liegen {len(pfadliste)} CSV-Dateien. Die Dateinamen lauten:\n{pfadliste}\n")

```

Als nächstes werden die Jahreszahlen aus den Pfadnamen extrahiert sowie die Spaltennamen ausgelesen.

Um die Jahreszahlen aus den Dateinamen zu extrahieren, können die Zeichenketten manuell beschnitten werden (Die Jahreszahl steht an den Indexpositionen 10 bis exklusiv 14). Alternativ kann ein regulärer Ausdruck verwendet werden. Reguläre Ausdrücke werden mit dem Modul re verarbeitet. Die Funktion `re.search(string = x, pattern = '[0-9]+')` sucht im Objekt x nach dem im Argument `pattern` spezifizierten Ausdruck, hier nach einer Zahl von 0 bis 9 `[0-9]` und jeder darauf folgenden Zahl `+`. Die Funktion `re.search()` erzeugt ein Match-Objekt, dessen Inhalt mit der Methode `Match.group()` ausgegeben werden kann, die einen string zurückgibt. (siehe [Dokumentation Modul re](https://docs.python.org/3/library/re.html#match-objects))

Um die Spaltennamen auszulesen, wird die Funktion `pd.read_csv()` mit den Argumenten `nrows = 1, header = 0` angewiesen, die erste Zeile auszulesen. Anschließend können die Spaltennamen visuell abgeglichen werden - dies ist im Reiter DataFrame der Spaltennamen umgesetzt. Für größere Datensätze ist dies aber nicht mehr praktikabel. Eine algorithmische Lösung ist im Reiter Spaltennamen finden umgesetzt. Dazu wird jede Spalte des DataFrames gegen alle anderen Spalten mit der Methode `pd.Series.isin(df)` abgeglichen.

:::: {.panel-tabset}

## Jahreszahlen und Spaltennamen auslesen
``` {python}
# Die Jahreszahlen auslesen
import re

jahreszahlen = []
for pfad in pfadliste:
  zwischenspeicher = re.search(string = pfad, pattern = '[0-9]+').group()
  jahreszahlen.append(int(zwischenspeicher))

print(f"Aus den Dateinamen extrahierte Jahreszahlen:\t{jahreszahlen}\n")

# Spaltennamen durch Einlesen der ersten Zeile extrahieren, header = None
i = 0
list_of_columns = []
for pfad in pfadliste:

  zwischenspeicher = pd.read_csv(filepath_or_buffer = ordnerpfad + '/' + pfad, 
  delimiter = ';', nrows = 1, header = None).transpose()

  list_of_columns.append(zwischenspeicher)
  i += 1

df_of_columns = pd.concat(list_of_columns, axis = 1, ignore_index = True)
df_of_columns.columns = jahreszahlen
```

Die Spaltennamen werden im nächsten Reiter ausgegeben.

## DataFrame der Spaltennamen
Mit der Ausgabe des DataFrames können die ungleichen Spaltennamen visuell identifiziert werden.

``` {python}
print(f"Ein DataFrame der Spaltennamen:\n{df_of_columns}")
```

## Spaltennamen finden
Der Abgleich der ungleichen Spaltennamen kann auch algorithmisch gelöst werden.

``` {python}
# Spaltennamen algorithmisch abgleichen
ungleiche_spaltennamen = pd.Series()

## vergleiche jede Spalte gegen alle anderen Spalten
for i in range(0, df_of_columns.shape[1]):

  aktuelle_spalte = df_of_columns.iloc[:, i]

  vergleichs_df = df_of_columns.drop(df_of_columns.columns[i], axis = 1)

  j = 0
  for vergleichsspalte in vergleichs_df: # vergleichsspalte ist der Spaltenname (als int) 2020, 2021 usw.
    
    # print(vergleichsspalte)
    maske_fehlender_spaltennamen = aktuelle_spalte.isin(vergleichs_df.loc[:, vergleichsspalte])
    maske_fehlender_spaltennamen = np.invert(maske_fehlender_spaltennamen) # pandas hat keine Methode .invert()
    
    # WENN Spaltennamen fehlen DANN
    if maske_fehlender_spaltennamen.sum() > 0:

      print(f"In den Unfalldaten {df_of_columns.columns[i]} treten die Spaltennamen {aktuelle_spalte[maske_fehlender_spaltennamen].values} auf, die nicht in den Unfalldaten {vergleichs_df.columns[j]} enthalten sind.\n")

      ungleiche_spaltennamen = pd.concat([ungleiche_spaltennamen, pd.Series(aktuelle_spalte[maske_fehlender_spaltennamen].values)])

    j +=1

ungleiche_spaltennamen = ungleiche_spaltennamen.dropna().unique()

print(f"Folgende Spaltennamen müssen vereinheitlicht werden:\n{ungleiche_spaltennamen}")

```

::::

&nbsp; 

Die Spaltennamen 'STRZUSTAND', 'IstStrassenzustand' und 'USTRZUSTAND' sowie 'OBJECTID', und 'OID_' müssen beim Einlesen der Daten vereinheitlicht werden. Die Spalte 'PLST' wurde nur im Jahr 2023 erhoben und kann entfallen (siehe Unfallatlas Metadaten). Dafür wird der Methode `pd.DataFrame.drop()` das Argument `errors = 'ignore'` übergeben, da in einem Datensatz nicht vorhandene Spalten andernfalls zu einer Fehlermeldung führen.

Die Spalte 'UIDENTSTLAE' enthält sehr große Ganzzahlen, weshalb diese als String eingelesen wird.

``` {python}

## Dateien einlesen
unfallatlas = pd.DataFrame()

for pfad in pfadliste:

  ### Datei einlesen
  zwischenspeicher = pd.read_csv(filepath_or_buffer = ordnerpfad + '/' + pfad, 
  delimiter = ';', dtype = {'UIDENTSTLAE': 'string'})

  ### Spaltennamen vereinheitlichen
  zwischenspeicher.rename(columns = {"IstStrassenzustand": "STRZUSTAND", "USTRZUSTAND": "STRZUSTAND", "OID_": "OBJECTID"}, inplace = True)
  zwischenspeicher.drop(columns = "PLST", inplace = True, errors = 'ignore')
  
  unfallatlas = pd.concat([unfallatlas, zwischenspeicher])

# Ausgabe
print(unfallatlas.info(), "\n")
unfallatlas.head()
```

&nbsp;

Abschließend kann der Datensatz aufgeräumt werden:

  - der Datensatz wird nach dem Jahr sortiert (wichtig: als erstes ausführen),
  
  - der Index wird zurückgesetzt (wichtig: als zweites),



  - die Spalte 'OBJECTID' wird neu erstellt, um die beim Einlesen erzeugten Duplikate zu entfernen und




``` {python}
# Datensatz nach Jahr sortieren
unfallatlas.sort_values(by = 'UJAHR', inplace = True)

# Index zurücksetzen
unfallatlas.reset_index(drop = True, inplace = True)

# Spalte 'OBJECTID' neu generieren
unfallatlas['OBJECTID'] = pd.Series(range(1, unfallatlas.shape[0] + 1))

print(unfallatlas.info(), "\n")
unfallatlas.head()
```

:::

